/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simple_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s3[12] = {10, 1, 0, 8, 0, 1, 2, 5, 6, 7, 8, 9};

static const casadi_real casadi_c0[3] = {2.5125628140703520e-04, 2.5125628140703520e-04, 5.0753692331117091e-05};
static const casadi_real casadi_c1[9] = {50., 0., 0., 0., 200., 0., 0., 0., 1281.};

/* simple_model_expl_vde_adj:(i0[8],i1[8],i2[2],i3[3])->(o0[10x1,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, w1, *w2=w+5, *w3=w+13, w4, w5, w6, w7, w8, w9, *w10=w+22, *w11=w+31, *w12=w+34, w13, w14, w15, *w16=w+40, *w17=w+43, *w18=w+52, *w19=w+55, w20, w21, w22, w23, w24, w25, *w26=w+64, *w27=w+67;
  /* #0: @0 = input[0][5] */
  w0 = arg[0] ? arg[0][5] : 0;
  /* #1: @1 = sin(@0) */
  w1 = sin( w0 );
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 8, w2);
  /* #3: {@3, @4, @5, @6, @7, @8} = vertsplit(@2) */
  casadi_copy(w2, 3, w3);
  w4 = w2[3];
  w5 = w2[4];
  w6 = w2[5];
  w7 = w2[6];
  w8 = w2[7];
  /* #4: @1 = (@1*@5) */
  w1 *= w5;
  /* #5: @9 = cos(@0) */
  w9 = cos( w0 );
  /* #6: @9 = (@9*@4) */
  w9 *= w4;
  /* #7: @1 = (@1+@9) */
  w1 += w9;
  /* #8: @9 = -3980 */
  w9 = -3980.;
  /* #9: @10 = zeros(3x3) */
  casadi_clear(w10, 9);
  /* #10: @11 = 
  [[0.000251256, 00, 00], 
   [00, 0.000251256, 00], 
   [00, 00, 5.07537e-05]] */
  casadi_copy(casadi_c0, 3, w11);
  /* #11: @11 = nonzeros(@11) */
  /* #12: @11 = (@11*@3) */
  for (i=0, rr=w11, cs=w3; i<3; ++i) (*rr++) *= (*cs++);
  /* #13: @12 = (-@11) */
  for (i=0, rr=w12, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #14: @13 = input[0][0] */
  w13 = arg[0] ? arg[0][0] : 0;
  /* #15: @14 = input[0][1] */
  w14 = arg[0] ? arg[0][1] : 0;
  /* #16: @15 = input[0][2] */
  w15 = arg[0] ? arg[0][2] : 0;
  /* #17: @16 = vertcat(@13, @14, @15) */
  rr=w16;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  /* #18: @16 = @16' */
  /* #19: @10 = mac(@12,@16,@10) */
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w12+j, tt=w16+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #20: @17 = @10' */
  for (i=0, rr=w17, cs=w10; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: {@16, @18, @19} = horzsplit(@17) */
  casadi_copy(w17, 3, w16);
  casadi_copy(w17+3, 3, w18);
  casadi_copy(w17+6, 3, w19);
  /* #22: @19 = @19' */
  /* #23: {@20, @21, NULL} = horzsplit(@19) */
  w20 = w19[0];
  w21 = w19[1];
  /* #24: @21 = (@9*@21) */
  w21  = (w9*w21);
  /* #25: @1 = (@1+@21) */
  w1 += w21;
  /* #26: @21 = 3980 */
  w21 = 3980.;
  /* #27: @18 = @18' */
  /* #28: {NULL, NULL, @22} = horzsplit(@18) */
  w22 = w18[2];
  /* #29: @22 = (@21*@22) */
  w22  = (w21*w22);
  /* #30: @1 = (@1+@22) */
  w1 += w22;
  /* #31: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #32: @22 = 0 */
  w22 = 0.;
  /* #33: @23 = 0 */
  w23 = 0.;
  /* #34: @24 = -3980 */
  w24 = -3980.;
  /* #35: @25 = (@24*@14) */
  w25  = (w24*w14);
  /* #36: @19 = horzcat(@22, @23, @25) */
  rr=w19;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w25;
  /* #37: @19 = @19' */
  /* #38: @22 = 0 */
  w22 = 0.;
  /* #39: @23 = 0 */
  w23 = 0.;
  /* #40: @21 = (@21*@13) */
  w21 *= w13;
  /* #41: @26 = horzcat(@22, @23, @21) */
  rr=w26;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w21;
  /* #42: @26 = @26' */
  /* #43: @22 = 3980 */
  w22 = 3980.;
  /* #44: @23 = (@22*@14) */
  w23  = (w22*w14);
  /* #45: @9 = (@9*@13) */
  w9 *= w13;
  /* #46: @21 = 0 */
  w21 = 0.;
  /* #47: @27 = horzcat(@23, @9, @21) */
  rr=w27;
  *rr++ = w23;
  *rr++ = w9;
  *rr++ = w21;
  /* #48: @27 = @27' */
  /* #49: @17 = horzcat(@19, @26, @27) */
  rr=w17;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  /* #50: @18 = mac(@17,@12,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #51: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #52: @17 = 
  [[50, -0, -0], 
   [-0, 200, -0], 
   [-0, -0, 1281]] */
  casadi_copy(casadi_c1, 9, w17);
  /* #53: @10 = @17' */
  for (i=0, rr=w10, cs=w17; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #54: @19 = (-@11) */
  for (i=0, rr=w19, cs=w11; i<3; ++i) *rr++ = (- *cs++ );
  /* #55: @12 = mac(@10,@19,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w19+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #56: @18 = (@18+@12) */
  for (i=0, rr=w18, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #57: {@23, @9, @21} = vertsplit(@18) */
  w23 = w18[0];
  w9 = w18[1];
  w21 = w18[2];
  /* #58: @1 = (@1+@23) */
  w1 += w23;
  /* #59: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #60: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #61: @1 = (@1*@5) */
  w1 *= w5;
  /* #62: @23 = sin(@0) */
  w23 = sin( w0 );
  /* #63: @23 = (@23*@4) */
  w23 *= w4;
  /* #64: @1 = (@1-@23) */
  w1 -= w23;
  /* #65: @22 = (@22*@20) */
  w22 *= w20;
  /* #66: @1 = (@1+@22) */
  w1 += w22;
  /* #67: @16 = @16' */
  /* #68: {NULL, NULL, @22} = horzsplit(@16) */
  w22 = w16[2];
  /* #69: @24 = (@24*@22) */
  w24 *= w22;
  /* #70: @1 = (@1+@24) */
  w1 += w24;
  /* #71: @1 = (@1+@9) */
  w1 += w9;
  /* #72: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #73: @1 = 3.5 */
  w1 = 3.5000000000000000e+00;
  /* #74: @9 = cos(@0) */
  w9 = cos( w0 );
  /* #75: @9 = (@9*@5) */
  w9 *= w5;
  /* #76: @9 = (@1*@9) */
  w9  = (w1*w9);
  /* #77: @6 = (@6+@9) */
  w6 += w9;
  /* #78: @9 = 3.5 */
  w9 = 3.5000000000000000e+00;
  /* #79: @24 = sin(@0) */
  w24 = sin( w0 );
  /* #80: @24 = (@24*@4) */
  w24 *= w4;
  /* #81: @24 = (@9*@24) */
  w24  = (w9*w24);
  /* #82: @6 = (@6-@24) */
  w6 -= w24;
  /* #83: @6 = (@6+@21) */
  w6 += w21;
  /* #84: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #85: @6 = sin(@0) */
  w6 = sin( w0 );
  /* #86: @21 = (@14*@5) */
  w21  = (w14*w5);
  /* #87: @6 = (@6*@21) */
  w6 *= w21;
  /* #88: @6 = (-@6) */
  w6 = (- w6 );
  /* #89: @21 = sin(@0) */
  w21 = sin( w0 );
  /* #90: @1 = (@1*@15) */
  w1 *= w15;
  /* #91: @1 = (@1*@5) */
  w1 *= w5;
  /* #92: @21 = (@21*@1) */
  w21 *= w1;
  /* #93: @6 = (@6-@21) */
  w6 -= w21;
  /* #94: @21 = cos(@0) */
  w21 = cos( w0 );
  /* #95: @5 = (@13*@5) */
  w5  = (w13*w5);
  /* #96: @21 = (@21*@5) */
  w21 *= w5;
  /* #97: @6 = (@6+@21) */
  w6 += w21;
  /* #98: @21 = cos(@0) */
  w21 = cos( w0 );
  /* #99: @9 = (@9*@15) */
  w9 *= w15;
  /* #100: @9 = (@9*@4) */
  w9 *= w4;
  /* #101: @21 = (@21*@9) */
  w21 *= w9;
  /* #102: @6 = (@6-@21) */
  w6 -= w21;
  /* #103: @21 = cos(@0) */
  w21 = cos( w0 );
  /* #104: @14 = (@14*@4) */
  w14 *= w4;
  /* #105: @21 = (@21*@14) */
  w21 *= w14;
  /* #106: @6 = (@6-@21) */
  w6 -= w21;
  /* #107: @21 = sin(@0) */
  w21 = sin( w0 );
  /* #108: @13 = (@13*@4) */
  w13 *= w4;
  /* #109: @21 = (@21*@13) */
  w21 *= w13;
  /* #110: @6 = (@6-@21) */
  w6 -= w21;
  /* #111: @21 = cos(@0) */
  w21 = cos( w0 );
  /* #112: @13 = input[3][0] */
  w13 = arg[3] ? arg[3][0] : 0;
  /* #113: @3 = (-@3) */
  for (i=0, rr=w3, cs=w3; i<3; ++i) *rr++ = (- *cs++ );
  /* #114: {@4, @14, NULL} = vertsplit(@3) */
  w4 = w3[0];
  w14 = w3[1];
  /* #115: @9 = (@13*@14) */
  w9  = (w13*w14);
  /* #116: @21 = (@21*@9) */
  w21 *= w9;
  /* #117: @6 = (@6+@21) */
  w6 += w21;
  /* #118: @21 = sin(@0) */
  w21 = sin( w0 );
  /* #119: @9 = input[3][1] */
  w9 = arg[3] ? arg[3][1] : 0;
  /* #120: @14 = (@9*@14) */
  w14  = (w9*w14);
  /* #121: @21 = (@21*@14) */
  w21 *= w14;
  /* #122: @6 = (@6-@21) */
  w6 -= w21;
  /* #123: @21 = cos(@0) */
  w21 = cos( w0 );
  /* #124: @9 = (@9*@4) */
  w9 *= w4;
  /* #125: @21 = (@21*@9) */
  w21 *= w9;
  /* #126: @6 = (@6-@21) */
  w6 -= w21;
  /* #127: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #128: @13 = (@13*@4) */
  w13 *= w4;
  /* #129: @0 = (@0*@13) */
  w0 *= w13;
  /* #130: @6 = (@6-@0) */
  w6 -= w0;
  /* #131: output[0][3] = @6 */
  if (res[0]) res[0][3] = w6;
  /* #132: {@6, @0, @13} = vertsplit(@11) */
  w6 = w11[0];
  w0 = w11[1];
  w13 = w11[2];
  /* #133: output[0][4] = @6 */
  if (res[0]) res[0][4] = w6;
  /* #134: @6 = -4 */
  w6 = -4.;
  /* #135: @6 = (@6*@13) */
  w6 *= w13;
  /* #136: @0 = (@0+@6) */
  w0 += w6;
  /* #137: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  /* #138: output[0][6] = @7 */
  if (res[0]) res[0][6] = w7;
  /* #139: output[0][7] = @8 */
  if (res[0]) res[0][7] = w8;
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real simple_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 70;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
