/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simple_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[10] = {3, 3, 0, 1, 2, 4, 2, 2, 0, 1};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[10] = {3, 3, 0, 2, 4, 4, 0, 1, 0, 1};
static const casadi_int casadi_s3[7] = {8, 2, 0, 1, 2, 6, 7};
static const casadi_int casadi_s4[13] = {2, 8, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1};
static const casadi_int casadi_s5[19] = {8, 2, 0, 7, 14, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 7};
static const casadi_int casadi_s6[17] = {8, 2, 0, 6, 12, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s8[75] = {8, 8, 0, 8, 16, 24, 32, 40, 48, 56, 64, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s9[21] = {8, 2, 0, 8, 16, 0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s10[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s11[3] = {0, 0, 0};
static const casadi_int casadi_s12[59] = {8, 8, 0, 6, 12, 18, 24, 30, 36, 42, 48, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

static const casadi_real casadi_c0[3] = {2.5125628140703520e-04, 2.5125628140703520e-04, 5.0753692331117091e-05};
static const casadi_real casadi_c1[9] = {50., 0., 0., 0., 200., 0., 0., 0., 1281.};
static const casadi_real casadi_c2[3] = {0., 0., 1.};

/* simple_model_expl_vde_forw:(i0[8],i1[8x8],i2[8x2],i3[2],i4[])->(o0[8],o1[8x8,48nz],o2[8x2,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+8, w1, w2, w3, w4, *w5=w+15, *w6=w+18, *w7=w+21, *w8=w+30, w9, w10, w11, *w12=w+36, w13, *w14=w+40, *w15=w+43, *w16=w+46, *w17=w+55, w18, *w19=w+65, *w20=w+74, *w21=w+138, *w22=w+146, *w23=w+154, *w24=w+162, *w25=w+170, *w26=w+178, *w27=w+186, *w28=w+194, w29, w30, w31, w32, *w35=w+206, *w36=w+208, *w37=w+212, *w38=w+216, w39, w40, w41, w42, *w43=w+222, *w44=w+224, *w45=w+238, *w46=w+254, *w47=w+260, *w48=w+266, *w49=w+278;
  /* #0: @0 = 
  [[0.000251256, 00, 00], 
   [00, 0.000251256, 00], 
   [00, 00, 5.07537e-05]] */
  casadi_copy(casadi_c0, 3, w0);
  /* #1: @0 = nonzeros(@0) */
  /* #2: @1 = input[0][6] */
  w1 = arg[0] ? arg[0][6] : 0;
  /* #3: @2 = input[0][7] */
  w2 = arg[0] ? arg[0][7] : 0;
  /* #4: @3 = 4 */
  w3 = 4.;
  /* #5: @4 = (@3*@2) */
  w4  = (w3*w2);
  /* #6: @5 = vertcat(@1, @2, @4) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w4;
  /* #7: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #8: @7 = 
  [[50, -0, -0], 
   [-0, 200, -0], 
   [-0, -0, 1281]] */
  casadi_copy(casadi_c1, 9, w7);
  /* #9: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #10: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #11: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #12: @8 = vertcat(@1, @2, @4) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w4;
  /* #13: @6 = mac(@7,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #14: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #15: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #16: @4 = 0 */
  w4 = 0.;
  /* #17: @9 = 0 */
  w9 = 0.;
  /* #18: @10 = -3980 */
  w10 = -3980.;
  /* #19: @11 = (@10*@2) */
  w11  = (w10*w2);
  /* #20: @12 = horzcat(@4, @9, @11) */
  rr=w12;
  *rr++ = w4;
  *rr++ = w9;
  *rr++ = w11;
  /* #21: @12 = @12' */
  /* #22: @4 = 0 */
  w4 = 0.;
  /* #23: @9 = 0 */
  w9 = 0.;
  /* #24: @11 = 3980 */
  w11 = 3980.;
  /* #25: @13 = (@11*@1) */
  w13  = (w11*w1);
  /* #26: @14 = horzcat(@4, @9, @13) */
  rr=w14;
  *rr++ = w4;
  *rr++ = w9;
  *rr++ = w13;
  /* #27: @14 = @14' */
  /* #28: @4 = 3980 */
  w4 = 3980.;
  /* #29: @2 = (@4*@2) */
  w2  = (w4*w2);
  /* #30: @9 = -3980 */
  w9 = -3980.;
  /* #31: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #32: @13 = 0 */
  w13 = 0.;
  /* #33: @15 = horzcat(@2, @1, @13) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w1;
  *rr++ = w13;
  /* #34: @15 = @15' */
  /* #35: @16 = horzcat(@12, @14, @15) */
  rr=w16;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  /* #36: @17 = @16' */
  for (i=0, rr=w17, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #37: @6 = mac(@17,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #38: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #39: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #40: output[0][0] = @5 */
  casadi_copy(w5, 3, res[0]);
  /* #41: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #42: @2 = input[0][5] */
  w2 = arg[0] ? arg[0][5] : 0;
  /* #43: @1 = cos(@2) */
  w1 = cos( w2 );
  /* #44: @13 = sin(@2) */
  w13 = sin( w2 );
  /* #45: @13 = (-@13) */
  w13 = (- w13 );
  /* #46: @18 = 0 */
  w18 = 0.;
  /* #47: @6 = horzcat(@1, @13, @18) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w13;
  *rr++ = w18;
  /* #48: @6 = @6' */
  /* #49: @1 = sin(@2) */
  w1 = sin( w2 );
  /* #50: @13 = cos(@2) */
  w13 = cos( w2 );
  /* #51: @18 = 0 */
  w18 = 0.;
  /* #52: @12 = horzcat(@1, @13, @18) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w13;
  *rr++ = w18;
  /* #53: @12 = @12' */
  /* #54: @14 = [[0, 0, 1]] */
  casadi_copy(casadi_c2, 3, w14);
  /* #55: @14 = @14' */
  /* #56: @16 = horzcat(@6, @12, @14) */
  rr=w16;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<3; ++i) *rr++ = *cs++;
  /* #57: @19 = @16' */
  for (i=0, rr=w19, cs=w16; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #58: @5 = mac(@19,@8,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #59: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+3);
  /* #60: @1 = input[3][0] */
  w1 = arg[3] ? arg[3][0] : 0;
  /* #61: output[0][2] = @1 */
  if (res[0]) res[0][6] = w1;
  /* #62: @1 = input[3][1] */
  w1 = arg[3] ? arg[3][1] : 0;
  /* #63: output[0][3] = @1 */
  if (res[0]) res[0][7] = w1;
  /* #64: @20 = input[1][0] */
  casadi_copy(arg[1], 64, w20);
  /* #65: {@21, @22, @23, @24, @25, @26, @27, @28} = horzsplit(@20) */
  casadi_copy(w20, 8, w21);
  casadi_copy(w20+8, 8, w22);
  casadi_copy(w20+16, 8, w23);
  casadi_copy(w20+24, 8, w24);
  casadi_copy(w20+32, 8, w25);
  casadi_copy(w20+40, 8, w26);
  casadi_copy(w20+48, 8, w27);
  casadi_copy(w20+56, 8, w28);
  /* #66: {@1, @13, @18, NULL, NULL, @29, @30, @31} = vertsplit(@21) */
  w1 = w21[0];
  w13 = w21[1];
  w18 = w21[2];
  w29 = w21[5];
  w30 = w21[6];
  w31 = w21[7];
  /* #67: @32 = (@3*@31) */
  w32  = (w3*w31);
  /* #68: @5 = vertcat(@30, @31, @32) */
  rr=w5;
  *rr++ = w30;
  *rr++ = w31;
  *rr++ = w32;
  /* #69: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #70: @12 = vertcat(@1, @13, @18) */
  rr=w12;
  *rr++ = w1;
  *rr++ = w13;
  *rr++ = w18;
  /* #71: @6 = mac(@7,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #72: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #73: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #74: @6 = mac(@17,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #75: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #76: @33 = 00 */
  /* #77: @34 = 00 */
  /* #78: @18 = (@10*@13) */
  w18  = (w10*w13);
  /* #79: @30 = horzcat(@33, @34, @18) */
  rr=(&w30);
  *rr++ = w18;
  /* #80: @30 = @30' */
  /* #81: @33 = 00 */
  /* #82: @34 = 00 */
  /* #83: @18 = (@11*@1) */
  w18  = (w11*w1);
  /* #84: @31 = horzcat(@33, @34, @18) */
  rr=(&w31);
  *rr++ = w18;
  /* #85: @31 = @31' */
  /* #86: @13 = (@4*@13) */
  w13  = (w4*w13);
  /* #87: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #88: @33 = 00 */
  /* #89: @35 = horzcat(@13, @1, @33) */
  rr=w35;
  *rr++ = w13;
  *rr++ = w1;
  /* #90: @35 = @35' */
  /* #91: @36 = horzcat(@30, @31, @35) */
  rr=w36;
  *rr++ = w30;
  *rr++ = w31;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #92: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #93: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #94: @6 = (@6+@14) */
  for (i=0, rr=w6, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #95: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #96: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #97: output[1][0] = @5 */
  casadi_copy(w5, 3, res[1]);
  /* #98: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #99: @5 = mac(@19,@12,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #100: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #101: @30 = sin(@2) */
  w30 = sin( w2 );
  /* #102: @31 = (@30*@29) */
  w31  = (w30*w29);
  /* #103: @31 = (-@31) */
  w31 = (- w31 );
  /* #104: @13 = cos(@2) */
  w13 = cos( w2 );
  /* #105: @1 = (@13*@29) */
  w1  = (w13*w29);
  /* #106: @1 = (-@1) */
  w1 = (- w1 );
  /* #107: @33 = 00 */
  /* #108: @35 = horzcat(@31, @1, @33) */
  rr=w35;
  *rr++ = w31;
  *rr++ = w1;
  /* #109: @35 = @35' */
  /* #110: @31 = cos(@2) */
  w31 = cos( w2 );
  /* #111: @1 = (@31*@29) */
  w1  = (w31*w29);
  /* #112: @18 = sin(@2) */
  w18 = sin( w2 );
  /* #113: @29 = (@18*@29) */
  w29  = (w18*w29);
  /* #114: @29 = (-@29) */
  w29 = (- w29 );
  /* #115: @33 = 00 */
  /* #116: @38 = horzcat(@1, @29, @33) */
  rr=w38;
  *rr++ = w1;
  *rr++ = w29;
  /* #117: @38 = @38' */
  /* #118: @33 = zeros(3x1,0nz) */
  /* #119: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #120: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #121: @12 = mac(@36,@8,@12) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w12, casadi_s1, w, 0);
  /* #122: @5 = (@5+@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #123: output[1][1] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+3);
  /* #124: {@1, @29, @32, NULL, NULL, @39, @40, @41} = vertsplit(@22) */
  w1 = w22[0];
  w29 = w22[1];
  w32 = w22[2];
  w39 = w22[5];
  w40 = w22[6];
  w41 = w22[7];
  /* #125: @42 = (@3*@41) */
  w42  = (w3*w41);
  /* #126: @5 = vertcat(@40, @41, @42) */
  rr=w5;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  /* #127: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #128: @6 = vertcat(@1, @29, @32) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w29;
  *rr++ = w32;
  /* #129: @12 = mac(@7,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #130: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #131: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #132: @12 = mac(@17,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #133: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #134: @33 = 00 */
  /* #135: @34 = 00 */
  /* #136: @32 = (@10*@29) */
  w32  = (w10*w29);
  /* #137: @40 = horzcat(@33, @34, @32) */
  rr=(&w40);
  *rr++ = w32;
  /* #138: @40 = @40' */
  /* #139: @33 = 00 */
  /* #140: @34 = 00 */
  /* #141: @32 = (@11*@1) */
  w32  = (w11*w1);
  /* #142: @41 = horzcat(@33, @34, @32) */
  rr=(&w41);
  *rr++ = w32;
  /* #143: @41 = @41' */
  /* #144: @29 = (@4*@29) */
  w29  = (w4*w29);
  /* #145: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #146: @33 = 00 */
  /* #147: @35 = horzcat(@29, @1, @33) */
  rr=w35;
  *rr++ = w29;
  *rr++ = w1;
  /* #148: @35 = @35' */
  /* #149: @36 = horzcat(@40, @41, @35) */
  rr=w36;
  *rr++ = w40;
  *rr++ = w41;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #150: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #151: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #152: @12 = (@12+@14) */
  for (i=0, rr=w12, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #153: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #154: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #155: output[1][2] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+6);
  /* #156: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #157: @5 = mac(@19,@6,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #158: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #159: @40 = (@30*@39) */
  w40  = (w30*w39);
  /* #160: @40 = (-@40) */
  w40 = (- w40 );
  /* #161: @41 = (@13*@39) */
  w41  = (w13*w39);
  /* #162: @41 = (-@41) */
  w41 = (- w41 );
  /* #163: @33 = 00 */
  /* #164: @35 = horzcat(@40, @41, @33) */
  rr=w35;
  *rr++ = w40;
  *rr++ = w41;
  /* #165: @35 = @35' */
  /* #166: @40 = (@31*@39) */
  w40  = (w31*w39);
  /* #167: @39 = (@18*@39) */
  w39  = (w18*w39);
  /* #168: @39 = (-@39) */
  w39 = (- w39 );
  /* #169: @33 = 00 */
  /* #170: @38 = horzcat(@40, @39, @33) */
  rr=w38;
  *rr++ = w40;
  *rr++ = w39;
  /* #171: @38 = @38' */
  /* #172: @33 = zeros(3x1,0nz) */
  /* #173: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #174: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #175: @6 = mac(@36,@8,@6) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w6, casadi_s1, w, 0);
  /* #176: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) += (*cs++);
  /* #177: output[1][3] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+9);
  /* #178: {@40, @39, @41, NULL, NULL, @29, @1, @32} = vertsplit(@23) */
  w40 = w23[0];
  w39 = w23[1];
  w41 = w23[2];
  w29 = w23[5];
  w1 = w23[6];
  w32 = w23[7];
  /* #179: @42 = (@3*@32) */
  w42  = (w3*w32);
  /* #180: @5 = vertcat(@1, @32, @42) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w32;
  *rr++ = w42;
  /* #181: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #182: @12 = vertcat(@40, @39, @41) */
  rr=w12;
  *rr++ = w40;
  *rr++ = w39;
  *rr++ = w41;
  /* #183: @6 = mac(@7,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #184: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #185: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #186: @6 = mac(@17,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #187: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #188: @33 = 00 */
  /* #189: @34 = 00 */
  /* #190: @41 = (@10*@39) */
  w41  = (w10*w39);
  /* #191: @1 = horzcat(@33, @34, @41) */
  rr=(&w1);
  *rr++ = w41;
  /* #192: @1 = @1' */
  /* #193: @33 = 00 */
  /* #194: @34 = 00 */
  /* #195: @41 = (@11*@40) */
  w41  = (w11*w40);
  /* #196: @32 = horzcat(@33, @34, @41) */
  rr=(&w32);
  *rr++ = w41;
  /* #197: @32 = @32' */
  /* #198: @39 = (@4*@39) */
  w39  = (w4*w39);
  /* #199: @40 = (@9*@40) */
  w40  = (w9*w40);
  /* #200: @33 = 00 */
  /* #201: @35 = horzcat(@39, @40, @33) */
  rr=w35;
  *rr++ = w39;
  *rr++ = w40;
  /* #202: @35 = @35' */
  /* #203: @36 = horzcat(@1, @32, @35) */
  rr=w36;
  *rr++ = w1;
  *rr++ = w32;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #204: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #205: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #206: @6 = (@6+@14) */
  for (i=0, rr=w6, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #207: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #208: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #209: output[1][4] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+12);
  /* #210: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #211: @5 = mac(@19,@12,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #212: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #213: @1 = (@30*@29) */
  w1  = (w30*w29);
  /* #214: @1 = (-@1) */
  w1 = (- w1 );
  /* #215: @32 = (@13*@29) */
  w32  = (w13*w29);
  /* #216: @32 = (-@32) */
  w32 = (- w32 );
  /* #217: @33 = 00 */
  /* #218: @35 = horzcat(@1, @32, @33) */
  rr=w35;
  *rr++ = w1;
  *rr++ = w32;
  /* #219: @35 = @35' */
  /* #220: @1 = (@31*@29) */
  w1  = (w31*w29);
  /* #221: @29 = (@18*@29) */
  w29  = (w18*w29);
  /* #222: @29 = (-@29) */
  w29 = (- w29 );
  /* #223: @33 = 00 */
  /* #224: @38 = horzcat(@1, @29, @33) */
  rr=w38;
  *rr++ = w1;
  *rr++ = w29;
  /* #225: @38 = @38' */
  /* #226: @33 = zeros(3x1,0nz) */
  /* #227: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #228: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #229: @12 = mac(@36,@8,@12) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w12, casadi_s1, w, 0);
  /* #230: @5 = (@5+@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #231: output[1][5] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+15);
  /* #232: {@1, @29, @32, NULL, NULL, @39, @40, @41} = vertsplit(@24) */
  w1 = w24[0];
  w29 = w24[1];
  w32 = w24[2];
  w39 = w24[5];
  w40 = w24[6];
  w41 = w24[7];
  /* #233: @42 = (@3*@41) */
  w42  = (w3*w41);
  /* #234: @5 = vertcat(@40, @41, @42) */
  rr=w5;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  /* #235: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #236: @6 = vertcat(@1, @29, @32) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w29;
  *rr++ = w32;
  /* #237: @12 = mac(@7,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #238: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #239: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #240: @12 = mac(@17,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #241: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #242: @33 = 00 */
  /* #243: @34 = 00 */
  /* #244: @32 = (@10*@29) */
  w32  = (w10*w29);
  /* #245: @40 = horzcat(@33, @34, @32) */
  rr=(&w40);
  *rr++ = w32;
  /* #246: @40 = @40' */
  /* #247: @33 = 00 */
  /* #248: @34 = 00 */
  /* #249: @32 = (@11*@1) */
  w32  = (w11*w1);
  /* #250: @41 = horzcat(@33, @34, @32) */
  rr=(&w41);
  *rr++ = w32;
  /* #251: @41 = @41' */
  /* #252: @29 = (@4*@29) */
  w29  = (w4*w29);
  /* #253: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #254: @33 = 00 */
  /* #255: @35 = horzcat(@29, @1, @33) */
  rr=w35;
  *rr++ = w29;
  *rr++ = w1;
  /* #256: @35 = @35' */
  /* #257: @36 = horzcat(@40, @41, @35) */
  rr=w36;
  *rr++ = w40;
  *rr++ = w41;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #258: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #259: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #260: @12 = (@12+@14) */
  for (i=0, rr=w12, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #261: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #262: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #263: output[1][6] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+18);
  /* #264: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #265: @5 = mac(@19,@6,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #266: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #267: @40 = (@30*@39) */
  w40  = (w30*w39);
  /* #268: @40 = (-@40) */
  w40 = (- w40 );
  /* #269: @41 = (@13*@39) */
  w41  = (w13*w39);
  /* #270: @41 = (-@41) */
  w41 = (- w41 );
  /* #271: @33 = 00 */
  /* #272: @35 = horzcat(@40, @41, @33) */
  rr=w35;
  *rr++ = w40;
  *rr++ = w41;
  /* #273: @35 = @35' */
  /* #274: @40 = (@31*@39) */
  w40  = (w31*w39);
  /* #275: @39 = (@18*@39) */
  w39  = (w18*w39);
  /* #276: @39 = (-@39) */
  w39 = (- w39 );
  /* #277: @33 = 00 */
  /* #278: @38 = horzcat(@40, @39, @33) */
  rr=w38;
  *rr++ = w40;
  *rr++ = w39;
  /* #279: @38 = @38' */
  /* #280: @33 = zeros(3x1,0nz) */
  /* #281: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #282: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #283: @6 = mac(@36,@8,@6) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w6, casadi_s1, w, 0);
  /* #284: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) += (*cs++);
  /* #285: output[1][7] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+21);
  /* #286: {@40, @39, @41, NULL, NULL, @29, @1, @32} = vertsplit(@25) */
  w40 = w25[0];
  w39 = w25[1];
  w41 = w25[2];
  w29 = w25[5];
  w1 = w25[6];
  w32 = w25[7];
  /* #287: @42 = (@3*@32) */
  w42  = (w3*w32);
  /* #288: @5 = vertcat(@1, @32, @42) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w32;
  *rr++ = w42;
  /* #289: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #290: @12 = vertcat(@40, @39, @41) */
  rr=w12;
  *rr++ = w40;
  *rr++ = w39;
  *rr++ = w41;
  /* #291: @6 = mac(@7,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #292: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #293: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #294: @6 = mac(@17,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #295: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #296: @33 = 00 */
  /* #297: @34 = 00 */
  /* #298: @41 = (@10*@39) */
  w41  = (w10*w39);
  /* #299: @1 = horzcat(@33, @34, @41) */
  rr=(&w1);
  *rr++ = w41;
  /* #300: @1 = @1' */
  /* #301: @33 = 00 */
  /* #302: @34 = 00 */
  /* #303: @41 = (@11*@40) */
  w41  = (w11*w40);
  /* #304: @32 = horzcat(@33, @34, @41) */
  rr=(&w32);
  *rr++ = w41;
  /* #305: @32 = @32' */
  /* #306: @39 = (@4*@39) */
  w39  = (w4*w39);
  /* #307: @40 = (@9*@40) */
  w40  = (w9*w40);
  /* #308: @33 = 00 */
  /* #309: @35 = horzcat(@39, @40, @33) */
  rr=w35;
  *rr++ = w39;
  *rr++ = w40;
  /* #310: @35 = @35' */
  /* #311: @36 = horzcat(@1, @32, @35) */
  rr=w36;
  *rr++ = w1;
  *rr++ = w32;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #312: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #313: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #314: @6 = (@6+@14) */
  for (i=0, rr=w6, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #315: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #316: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #317: output[1][8] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+24);
  /* #318: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #319: @5 = mac(@19,@12,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #320: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #321: @1 = (@30*@29) */
  w1  = (w30*w29);
  /* #322: @1 = (-@1) */
  w1 = (- w1 );
  /* #323: @32 = (@13*@29) */
  w32  = (w13*w29);
  /* #324: @32 = (-@32) */
  w32 = (- w32 );
  /* #325: @33 = 00 */
  /* #326: @35 = horzcat(@1, @32, @33) */
  rr=w35;
  *rr++ = w1;
  *rr++ = w32;
  /* #327: @35 = @35' */
  /* #328: @1 = (@31*@29) */
  w1  = (w31*w29);
  /* #329: @29 = (@18*@29) */
  w29  = (w18*w29);
  /* #330: @29 = (-@29) */
  w29 = (- w29 );
  /* #331: @33 = 00 */
  /* #332: @38 = horzcat(@1, @29, @33) */
  rr=w38;
  *rr++ = w1;
  *rr++ = w29;
  /* #333: @38 = @38' */
  /* #334: @33 = zeros(3x1,0nz) */
  /* #335: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #336: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #337: @12 = mac(@36,@8,@12) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w12, casadi_s1, w, 0);
  /* #338: @5 = (@5+@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #339: output[1][9] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+27);
  /* #340: {@1, @29, @32, NULL, NULL, @39, @40, @41} = vertsplit(@26) */
  w1 = w26[0];
  w29 = w26[1];
  w32 = w26[2];
  w39 = w26[5];
  w40 = w26[6];
  w41 = w26[7];
  /* #341: @42 = (@3*@41) */
  w42  = (w3*w41);
  /* #342: @5 = vertcat(@40, @41, @42) */
  rr=w5;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  /* #343: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #344: @6 = vertcat(@1, @29, @32) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w29;
  *rr++ = w32;
  /* #345: @12 = mac(@7,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #346: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #347: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #348: @12 = mac(@17,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #349: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #350: @33 = 00 */
  /* #351: @34 = 00 */
  /* #352: @32 = (@10*@29) */
  w32  = (w10*w29);
  /* #353: @40 = horzcat(@33, @34, @32) */
  rr=(&w40);
  *rr++ = w32;
  /* #354: @40 = @40' */
  /* #355: @33 = 00 */
  /* #356: @34 = 00 */
  /* #357: @32 = (@11*@1) */
  w32  = (w11*w1);
  /* #358: @41 = horzcat(@33, @34, @32) */
  rr=(&w41);
  *rr++ = w32;
  /* #359: @41 = @41' */
  /* #360: @29 = (@4*@29) */
  w29  = (w4*w29);
  /* #361: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #362: @33 = 00 */
  /* #363: @35 = horzcat(@29, @1, @33) */
  rr=w35;
  *rr++ = w29;
  *rr++ = w1;
  /* #364: @35 = @35' */
  /* #365: @36 = horzcat(@40, @41, @35) */
  rr=w36;
  *rr++ = w40;
  *rr++ = w41;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #366: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #367: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #368: @12 = (@12+@14) */
  for (i=0, rr=w12, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #369: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #370: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #371: output[1][10] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+30);
  /* #372: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #373: @5 = mac(@19,@6,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #374: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #375: @40 = (@30*@39) */
  w40  = (w30*w39);
  /* #376: @40 = (-@40) */
  w40 = (- w40 );
  /* #377: @41 = (@13*@39) */
  w41  = (w13*w39);
  /* #378: @41 = (-@41) */
  w41 = (- w41 );
  /* #379: @33 = 00 */
  /* #380: @35 = horzcat(@40, @41, @33) */
  rr=w35;
  *rr++ = w40;
  *rr++ = w41;
  /* #381: @35 = @35' */
  /* #382: @40 = (@31*@39) */
  w40  = (w31*w39);
  /* #383: @39 = (@18*@39) */
  w39  = (w18*w39);
  /* #384: @39 = (-@39) */
  w39 = (- w39 );
  /* #385: @33 = 00 */
  /* #386: @38 = horzcat(@40, @39, @33) */
  rr=w38;
  *rr++ = w40;
  *rr++ = w39;
  /* #387: @38 = @38' */
  /* #388: @33 = zeros(3x1,0nz) */
  /* #389: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #390: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #391: @6 = mac(@36,@8,@6) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w6, casadi_s1, w, 0);
  /* #392: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) += (*cs++);
  /* #393: output[1][11] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+33);
  /* #394: {@40, @39, @41, NULL, NULL, @29, @1, @32} = vertsplit(@27) */
  w40 = w27[0];
  w39 = w27[1];
  w41 = w27[2];
  w29 = w27[5];
  w1 = w27[6];
  w32 = w27[7];
  /* #395: @42 = (@3*@32) */
  w42  = (w3*w32);
  /* #396: @5 = vertcat(@1, @32, @42) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w32;
  *rr++ = w42;
  /* #397: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #398: @12 = vertcat(@40, @39, @41) */
  rr=w12;
  *rr++ = w40;
  *rr++ = w39;
  *rr++ = w41;
  /* #399: @6 = mac(@7,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #400: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #401: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #402: @6 = mac(@17,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #403: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #404: @33 = 00 */
  /* #405: @34 = 00 */
  /* #406: @41 = (@10*@39) */
  w41  = (w10*w39);
  /* #407: @1 = horzcat(@33, @34, @41) */
  rr=(&w1);
  *rr++ = w41;
  /* #408: @1 = @1' */
  /* #409: @33 = 00 */
  /* #410: @34 = 00 */
  /* #411: @41 = (@11*@40) */
  w41  = (w11*w40);
  /* #412: @32 = horzcat(@33, @34, @41) */
  rr=(&w32);
  *rr++ = w41;
  /* #413: @32 = @32' */
  /* #414: @39 = (@4*@39) */
  w39  = (w4*w39);
  /* #415: @40 = (@9*@40) */
  w40  = (w9*w40);
  /* #416: @33 = 00 */
  /* #417: @35 = horzcat(@39, @40, @33) */
  rr=w35;
  *rr++ = w39;
  *rr++ = w40;
  /* #418: @35 = @35' */
  /* #419: @36 = horzcat(@1, @32, @35) */
  rr=w36;
  *rr++ = w1;
  *rr++ = w32;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #420: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #421: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #422: @6 = (@6+@14) */
  for (i=0, rr=w6, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #423: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #424: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #425: output[1][12] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+36);
  /* #426: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #427: @5 = mac(@19,@12,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #428: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #429: @1 = (@30*@29) */
  w1  = (w30*w29);
  /* #430: @1 = (-@1) */
  w1 = (- w1 );
  /* #431: @32 = (@13*@29) */
  w32  = (w13*w29);
  /* #432: @32 = (-@32) */
  w32 = (- w32 );
  /* #433: @33 = 00 */
  /* #434: @35 = horzcat(@1, @32, @33) */
  rr=w35;
  *rr++ = w1;
  *rr++ = w32;
  /* #435: @35 = @35' */
  /* #436: @1 = (@31*@29) */
  w1  = (w31*w29);
  /* #437: @29 = (@18*@29) */
  w29  = (w18*w29);
  /* #438: @29 = (-@29) */
  w29 = (- w29 );
  /* #439: @33 = 00 */
  /* #440: @38 = horzcat(@1, @29, @33) */
  rr=w38;
  *rr++ = w1;
  *rr++ = w29;
  /* #441: @38 = @38' */
  /* #442: @33 = zeros(3x1,0nz) */
  /* #443: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #444: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #445: @12 = mac(@36,@8,@12) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w12, casadi_s1, w, 0);
  /* #446: @5 = (@5+@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #447: output[1][13] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+39);
  /* #448: {@1, @29, @32, NULL, NULL, @39, @40, @41} = vertsplit(@28) */
  w1 = w28[0];
  w29 = w28[1];
  w32 = w28[2];
  w39 = w28[5];
  w40 = w28[6];
  w41 = w28[7];
  /* #449: @42 = (@3*@41) */
  w42  = (w3*w41);
  /* #450: @5 = vertcat(@40, @41, @42) */
  rr=w5;
  *rr++ = w40;
  *rr++ = w41;
  *rr++ = w42;
  /* #451: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #452: @6 = vertcat(@1, @29, @32) */
  rr=w6;
  *rr++ = w1;
  *rr++ = w29;
  *rr++ = w32;
  /* #453: @12 = mac(@7,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #454: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #455: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #456: @12 = mac(@17,@6,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #457: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #458: @33 = 00 */
  /* #459: @34 = 00 */
  /* #460: @32 = (@10*@29) */
  w32  = (w10*w29);
  /* #461: @40 = horzcat(@33, @34, @32) */
  rr=(&w40);
  *rr++ = w32;
  /* #462: @40 = @40' */
  /* #463: @33 = 00 */
  /* #464: @34 = 00 */
  /* #465: @32 = (@11*@1) */
  w32  = (w11*w1);
  /* #466: @41 = horzcat(@33, @34, @32) */
  rr=(&w41);
  *rr++ = w32;
  /* #467: @41 = @41' */
  /* #468: @29 = (@4*@29) */
  w29  = (w4*w29);
  /* #469: @1 = (@9*@1) */
  w1  = (w9*w1);
  /* #470: @33 = 00 */
  /* #471: @35 = horzcat(@29, @1, @33) */
  rr=w35;
  *rr++ = w29;
  *rr++ = w1;
  /* #472: @35 = @35' */
  /* #473: @36 = horzcat(@40, @41, @35) */
  rr=w36;
  *rr++ = w40;
  *rr++ = w41;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #474: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #475: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #476: @12 = (@12+@14) */
  for (i=0, rr=w12, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #477: @5 = (@5-@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) -= (*cs++);
  /* #478: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #479: output[1][14] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+42);
  /* #480: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #481: @5 = mac(@19,@6,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #482: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #483: @30 = (@30*@39) */
  w30 *= w39;
  /* #484: @30 = (-@30) */
  w30 = (- w30 );
  /* #485: @13 = (@13*@39) */
  w13 *= w39;
  /* #486: @13 = (-@13) */
  w13 = (- w13 );
  /* #487: @33 = 00 */
  /* #488: @35 = horzcat(@30, @13, @33) */
  rr=w35;
  *rr++ = w30;
  *rr++ = w13;
  /* #489: @35 = @35' */
  /* #490: @31 = (@31*@39) */
  w31 *= w39;
  /* #491: @18 = (@18*@39) */
  w18 *= w39;
  /* #492: @18 = (-@18) */
  w18 = (- w18 );
  /* #493: @33 = 00 */
  /* #494: @38 = horzcat(@31, @18, @33) */
  rr=w38;
  *rr++ = w31;
  *rr++ = w18;
  /* #495: @38 = @38' */
  /* #496: @33 = zeros(3x1,0nz) */
  /* #497: @37 = horzcat(@35, @38, @33) */
  rr=w37;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #498: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #499: @6 = mac(@36,@8,@6) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w6, casadi_s1, w, 0);
  /* #500: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) += (*cs++);
  /* #501: output[1][15] = @5 */
  if (res[1]) casadi_copy(w5, 3, res[1]+45);
  /* #502: @35 = zeros(2x8,2nz) */
  casadi_clear(w35, 2);
  /* #503: @33 = zeros(3x1,0nz) */
  /* #504: @34 = zeros(3x1,0nz) */
  /* #505: @38 = ones(2x1) */
  casadi_fill(w38, 2, 1.);
  /* #506: {@31, @18} = vertsplit(@38) */
  w31 = w38[0];
  w18 = w38[1];
  /* #507: @38 = vertcat(@33, @34, @31, @18) */
  rr=w38;
  *rr++ = w31;
  *rr++ = w18;
  /* #508: @43 = @38[:2] */
  for (rr=w43, ss=w38+0; ss!=w38+2; ss+=1) *rr++ = *ss;
  /* #509: (@35[:2] = @43) */
  for (rr=w35+0, ss=w43; rr!=w35+2; rr+=1) *rr = *ss++;
  /* #510: @43 = @35' */
  casadi_trans(w35,casadi_s4, w43, casadi_s3, iw);
  /* #511: @44 = project(@43) */
  casadi_project(w43, casadi_s3, w44, casadi_s5, w);
  /* #512: @45 = input[2][0] */
  casadi_copy(arg[2], 16, w45);
  /* #513: {@28, @27} = horzsplit(@45) */
  casadi_copy(w45, 8, w28);
  casadi_copy(w45+8, 8, w27);
  /* #514: {@31, @18, @39, NULL, NULL, @30, @13, @40} = vertsplit(@28) */
  w31 = w28[0];
  w18 = w28[1];
  w39 = w28[2];
  w30 = w28[5];
  w13 = w28[6];
  w40 = w28[7];
  /* #515: @41 = (@3*@40) */
  w41  = (w3*w40);
  /* #516: @5 = vertcat(@13, @40, @41) */
  rr=w5;
  *rr++ = w13;
  *rr++ = w40;
  *rr++ = w41;
  /* #517: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #518: @12 = vertcat(@31, @18, @39) */
  rr=w12;
  *rr++ = w31;
  *rr++ = w18;
  *rr++ = w39;
  /* #519: @6 = mac(@7,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #520: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #521: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #522: @6 = mac(@17,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #523: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #524: @33 = 00 */
  /* #525: @34 = 00 */
  /* #526: @39 = (@10*@18) */
  w39  = (w10*w18);
  /* #527: @13 = horzcat(@33, @34, @39) */
  rr=(&w13);
  *rr++ = w39;
  /* #528: @13 = @13' */
  /* #529: @33 = 00 */
  /* #530: @34 = 00 */
  /* #531: @39 = (@11*@31) */
  w39  = (w11*w31);
  /* #532: @40 = horzcat(@33, @34, @39) */
  rr=(&w40);
  *rr++ = w39;
  /* #533: @40 = @40' */
  /* #534: @18 = (@4*@18) */
  w18  = (w4*w18);
  /* #535: @31 = (@9*@31) */
  w31  = (w9*w31);
  /* #536: @33 = 00 */
  /* #537: @43 = horzcat(@18, @31, @33) */
  rr=w43;
  *rr++ = w18;
  *rr++ = w31;
  /* #538: @43 = @43' */
  /* #539: @36 = horzcat(@13, @40, @43) */
  rr=w36;
  *rr++ = w13;
  *rr++ = w40;
  for (i=0, cs=w43; i<2; ++i) *rr++ = *cs++;
  /* #540: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #541: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #542: @6 = (@6+@14) */
  for (i=0, rr=w6, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #543: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #544: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #545: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #546: @6 = mac(@19,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #547: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #548: @13 = sin(@2) */
  w13 = sin( w2 );
  /* #549: @40 = (@13*@30) */
  w40  = (w13*w30);
  /* #550: @40 = (-@40) */
  w40 = (- w40 );
  /* #551: @18 = cos(@2) */
  w18 = cos( w2 );
  /* #552: @31 = (@18*@30) */
  w31  = (w18*w30);
  /* #553: @31 = (-@31) */
  w31 = (- w31 );
  /* #554: @33 = 00 */
  /* #555: @43 = horzcat(@40, @31, @33) */
  rr=w43;
  *rr++ = w40;
  *rr++ = w31;
  /* #556: @43 = @43' */
  /* #557: @40 = cos(@2) */
  w40 = cos( w2 );
  /* #558: @31 = (@40*@30) */
  w31  = (w40*w30);
  /* #559: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #560: @30 = (@2*@30) */
  w30  = (w2*w30);
  /* #561: @30 = (-@30) */
  w30 = (- w30 );
  /* #562: @33 = 00 */
  /* #563: @35 = horzcat(@31, @30, @33) */
  rr=w35;
  *rr++ = w31;
  *rr++ = w30;
  /* #564: @35 = @35' */
  /* #565: @33 = zeros(3x1,0nz) */
  /* #566: @37 = horzcat(@43, @35, @33) */
  rr=w37;
  for (i=0, cs=w43; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #567: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #568: @12 = mac(@36,@8,@12) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w12, casadi_s1, w, 0);
  /* #569: @6 = (@6+@12) */
  for (i=0, rr=w6, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #570: @33 = 00 */
  /* #571: @34 = 00 */
  /* #572: @46 = vertcat(@5, @6, @33, @34) */
  rr=w46;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  /* #573: {@31, @30, @39, NULL, NULL, @41, @29, @1} = vertsplit(@27) */
  w31 = w27[0];
  w30 = w27[1];
  w39 = w27[2];
  w41 = w27[5];
  w29 = w27[6];
  w1 = w27[7];
  /* #574: @3 = (@3*@1) */
  w3 *= w1;
  /* #575: @5 = vertcat(@29, @1, @3) */
  rr=w5;
  *rr++ = w29;
  *rr++ = w1;
  *rr++ = w3;
  /* #576: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #577: @12 = vertcat(@31, @30, @39) */
  rr=w12;
  *rr++ = w31;
  *rr++ = w30;
  *rr++ = w39;
  /* #578: @6 = mac(@7,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #579: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #580: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #581: @6 = mac(@17,@12,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #582: @14 = zeros(3x1) */
  casadi_clear(w14, 3);
  /* #583: @33 = 00 */
  /* #584: @34 = 00 */
  /* #585: @10 = (@10*@30) */
  w10 *= w30;
  /* #586: @39 = horzcat(@33, @34, @10) */
  rr=(&w39);
  *rr++ = w10;
  /* #587: @39 = @39' */
  /* #588: @33 = 00 */
  /* #589: @34 = 00 */
  /* #590: @11 = (@11*@31) */
  w11 *= w31;
  /* #591: @10 = horzcat(@33, @34, @11) */
  rr=(&w10);
  *rr++ = w11;
  /* #592: @10 = @10' */
  /* #593: @4 = (@4*@30) */
  w4 *= w30;
  /* #594: @9 = (@9*@31) */
  w9 *= w31;
  /* #595: @33 = 00 */
  /* #596: @43 = horzcat(@4, @9, @33) */
  rr=w43;
  *rr++ = w4;
  *rr++ = w9;
  /* #597: @43 = @43' */
  /* #598: @36 = horzcat(@39, @10, @43) */
  rr=w36;
  *rr++ = w39;
  *rr++ = w10;
  for (i=0, cs=w43; i<2; ++i) *rr++ = *cs++;
  /* #599: @37 = @36' */
  casadi_trans(w36,casadi_s0, w37, casadi_s0, iw);
  /* #600: @14 = mac(@37,@8,@14) */
  casadi_mtimes(w37, casadi_s0, w8, casadi_s1, w14, casadi_s1, w, 0);
  /* #601: @6 = (@6+@14) */
  for (i=0, rr=w6, cs=w14; i<3; ++i) (*rr++) += (*cs++);
  /* #602: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #603: @0 = (@0*@5) */
  for (i=0, rr=w0, cs=w5; i<3; ++i) (*rr++) *= (*cs++);
  /* #604: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #605: @5 = mac(@19,@12,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #606: @12 = zeros(3x1) */
  casadi_clear(w12, 3);
  /* #607: @13 = (@13*@41) */
  w13 *= w41;
  /* #608: @13 = (-@13) */
  w13 = (- w13 );
  /* #609: @18 = (@18*@41) */
  w18 *= w41;
  /* #610: @18 = (-@18) */
  w18 = (- w18 );
  /* #611: @33 = 00 */
  /* #612: @43 = horzcat(@13, @18, @33) */
  rr=w43;
  *rr++ = w13;
  *rr++ = w18;
  /* #613: @43 = @43' */
  /* #614: @40 = (@40*@41) */
  w40 *= w41;
  /* #615: @2 = (@2*@41) */
  w2 *= w41;
  /* #616: @2 = (-@2) */
  w2 = (- w2 );
  /* #617: @33 = 00 */
  /* #618: @35 = horzcat(@40, @2, @33) */
  rr=w35;
  *rr++ = w40;
  *rr++ = w2;
  /* #619: @35 = @35' */
  /* #620: @33 = zeros(3x1,0nz) */
  /* #621: @37 = horzcat(@43, @35, @33) */
  rr=w37;
  for (i=0, cs=w43; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #622: @36 = @37' */
  casadi_trans(w37,casadi_s2, w36, casadi_s2, iw);
  /* #623: @12 = mac(@36,@8,@12) */
  casadi_mtimes(w36, casadi_s2, w8, casadi_s1, w12, casadi_s1, w, 0);
  /* #624: @5 = (@5+@12) */
  for (i=0, rr=w5, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #625: @33 = 00 */
  /* #626: @34 = 00 */
  /* #627: @47 = vertcat(@0, @5, @33, @34) */
  rr=w47;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #628: @48 = horzcat(@46, @47) */
  rr=w48;
  for (i=0, cs=w46; i<6; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<6; ++i) *rr++ = *cs++;
  /* #629: @49 = project(@48) */
  casadi_project(w48, casadi_s6, w49, casadi_s5, w);
  /* #630: @44 = (@44+@49) */
  for (i=0, rr=w44, cs=w49; i<14; ++i) (*rr++) += (*cs++);
  /* #631: output[2][0] = @44 */
  casadi_copy(w44, 14, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real simple_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    case 3: return casadi_s10;
    case 4: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    case 1: return casadi_s12;
    case 2: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 11;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 292;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
