/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simple_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s1[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[12] = {11, 1, 0, 8, 0, 1, 2, 5, 6, 7, 9, 10};

static const casadi_real casadi_c0[3] = {2.5125628140703520e-04, 2.5125628140703520e-04, 5.0753692331117091e-05};
static const casadi_real casadi_c1[3] = {0., 0., 1.};
static const casadi_real casadi_c2[9] = {50., 0., 0., 0., 200., 0., 0., 0., 1281.};

/* simple_model_expl_vde_adj:(i0[9],i1[9],i2[2],i3[])->(o0[11x1,8nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real w0, *w1=w+4, *w2=w+13, w3, w4, w5, w6, *w7=w+20, *w8=w+23, *w9=w+32, *w10=w+35, w11, w12, w13, *w14=w+41, *w15=w+44, *w16=w+47, *w17=w+50, w18, w19, w20, w21, w22, w23, w24, *w25=w+60, *w26=w+63, w27, *w28=w+67, *w29=w+70;
  /* #0: @0 = -3980 */
  w0 = -3980.;
  /* #1: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #2: @2 = 
  [[0.000251256, 00, 00], 
   [00, 0.000251256, 00], 
   [00, 00, 5.07537e-05]] */
  casadi_copy(casadi_c0, 3, w2);
  /* #3: @2 = nonzeros(@2) */
  /* #4: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #5: @4 = cos(@3) */
  w4 = cos( w3 );
  /* #6: @5 = sin(@3) */
  w5 = sin( w3 );
  /* #7: @5 = (-@5) */
  w5 = (- w5 );
  /* #8: @6 = 0 */
  w6 = 0.;
  /* #9: @7 = horzcat(@4, @5, @6) */
  rr=w7;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  /* #10: @7 = @7' */
  /* #11: @8 = input[1][0] */
  casadi_copy(arg[1], 9, w8);
  /* #12: {@9, @10, @4, @5, @6} = vertsplit(@8) */
  casadi_copy(w8, 3, w9);
  casadi_copy(w8+3, 3, w10);
  w4 = w8[6];
  w5 = w8[7];
  w6 = w8[8];
  /* #13: @7 = (@7*@6) */
  for (i=0, rr=w7; i<3; ++i) (*rr++) *= w6;
  /* #14: @7 = (@7+@9) */
  for (i=0, rr=w7, cs=w9; i<3; ++i) (*rr++) += (*cs++);
  /* #15: @7 = (@2*@7) */
  for (i=0, rr=w7, cr=w2, cs=w7; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #16: @9 = (-@7) */
  for (i=0, rr=w9, cs=w7; i<3; ++i) *rr++ = (- *cs++ );
  /* #17: @11 = input[0][0] */
  w11 = arg[0] ? arg[0][0] : 0;
  /* #18: @12 = input[0][1] */
  w12 = arg[0] ? arg[0][1] : 0;
  /* #19: @13 = input[0][2] */
  w13 = arg[0] ? arg[0][2] : 0;
  /* #20: @14 = vertcat(@11, @12, @13) */
  rr=w14;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  /* #21: @15 = @14' */
  casadi_copy(w14, 3, w15);
  /* #22: @1 = mac(@9,@15,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w15+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #23: @8 = @1' */
  for (i=0, rr=w8, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #24: {@15, @16, @17} = horzsplit(@8) */
  casadi_copy(w8, 3, w15);
  casadi_copy(w8+3, 3, w16);
  casadi_copy(w8+6, 3, w17);
  /* #25: @17 = @17' */
  /* #26: {@18, @19, NULL} = horzsplit(@17) */
  w18 = w17[0];
  w19 = w17[1];
  /* #27: @19 = (@0*@19) */
  w19  = (w0*w19);
  /* #28: @20 = sin(@3) */
  w20 = sin( w3 );
  /* #29: @20 = (@20*@6) */
  w20 *= w6;
  /* #30: @21 = (@13*@20) */
  w21  = (w13*w20);
  /* #31: @19 = (@19-@21) */
  w19 -= w21;
  /* #32: @21 = 3980 */
  w21 = 3980.;
  /* #33: @16 = @16' */
  /* #34: {NULL, NULL, @22} = horzsplit(@16) */
  w22 = w16[2];
  /* #35: @22 = (@21*@22) */
  w22  = (w21*w22);
  /* #36: @19 = (@19+@22) */
  w19 += w22;
  /* #37: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #38: @22 = cos(@3) */
  w22 = cos( w3 );
  /* #39: @23 = sin(@3) */
  w23 = sin( w3 );
  /* #40: @23 = (-@23) */
  w23 = (- w23 );
  /* #41: @24 = 0 */
  w24 = 0.;
  /* #42: @17 = horzcat(@22, @23, @24) */
  rr=w17;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  /* #43: @17 = @17' */
  /* #44: @22 = sin(@3) */
  w22 = sin( w3 );
  /* #45: @23 = cos(@3) */
  w23 = cos( w3 );
  /* #46: @24 = 0 */
  w24 = 0.;
  /* #47: @25 = horzcat(@22, @23, @24) */
  rr=w25;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  /* #48: @25 = @25' */
  /* #49: @26 = [[0, 0, 1]] */
  casadi_copy(casadi_c1, 3, w26);
  /* #50: @26 = @26' */
  /* #51: @8 = horzcat(@17, @25, @26) */
  rr=w8;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  /* #52: @16 = mac(@8,@10,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #53: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #54: @22 = 0 */
  w22 = 0.;
  /* #55: @23 = 0 */
  w23 = 0.;
  /* #56: @24 = -3980 */
  w24 = -3980.;
  /* #57: @27 = (@24*@12) */
  w27  = (w24*w12);
  /* #58: @25 = horzcat(@22, @23, @27) */
  rr=w25;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w27;
  /* #59: @25 = @25' */
  /* #60: @22 = 0 */
  w22 = 0.;
  /* #61: @23 = 0 */
  w23 = 0.;
  /* #62: @21 = (@21*@11) */
  w21 *= w11;
  /* #63: @26 = horzcat(@22, @23, @21) */
  rr=w26;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w21;
  /* #64: @26 = @26' */
  /* #65: @22 = 3980 */
  w22 = 3980.;
  /* #66: @23 = (@22*@12) */
  w23  = (w22*w12);
  /* #67: @0 = (@0*@11) */
  w0 *= w11;
  /* #68: @21 = 0 */
  w21 = 0.;
  /* #69: @28 = horzcat(@23, @0, @21) */
  rr=w28;
  *rr++ = w23;
  *rr++ = w0;
  *rr++ = w21;
  /* #70: @28 = @28' */
  /* #71: @8 = horzcat(@25, @26, @28) */
  rr=w8;
  for (i=0, cs=w25; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #72: @17 = mac(@8,@9,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #73: @16 = (@16+@17) */
  for (i=0, rr=w16, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #74: @17 = zeros(3x1) */
  casadi_clear(w17, 3);
  /* #75: @1 = 
  [[50, -0, -0], 
   [-0, 200, -0], 
   [-0, -0, 1281]] */
  casadi_copy(casadi_c2, 9, w1);
  /* #76: @29 = @1' */
  for (i=0, rr=w29, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #77: @9 = (-@7) */
  for (i=0, rr=w9, cs=w7; i<3; ++i) *rr++ = (- *cs++ );
  /* #78: @17 = mac(@29,@9,@17) */
  for (i=0, rr=w17; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w29+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #79: @16 = (@16+@17) */
  for (i=0, rr=w16, cs=w17; i<3; ++i) (*rr++) += (*cs++);
  /* #80: {@23, @0, @21} = vertsplit(@16) */
  w23 = w16[0];
  w0 = w16[1];
  w21 = w16[2];
  /* #81: @19 = (@19+@23) */
  w19 += w23;
  /* #82: output[0][0] = @19 */
  if (res[0]) res[0][0] = w19;
  /* #83: @22 = (@22*@18) */
  w22 *= w18;
  /* #84: @18 = cos(@3) */
  w18 = cos( w3 );
  /* #85: @18 = (@18*@6) */
  w18 *= w6;
  /* #86: @19 = (@13*@18) */
  w19  = (w13*w18);
  /* #87: @22 = (@22-@19) */
  w22 -= w19;
  /* #88: @15 = @15' */
  /* #89: {NULL, NULL, @19} = horzsplit(@15) */
  w19 = w15[2];
  /* #90: @24 = (@24*@19) */
  w24 *= w19;
  /* #91: @22 = (@22+@24) */
  w22 += w24;
  /* #92: @22 = (@22+@0) */
  w22 += w0;
  /* #93: output[0][1] = @22 */
  if (res[0]) res[0][1] = w22;
  /* #94: @20 = (@11*@20) */
  w20  = (w11*w20);
  /* #95: @20 = (-@20) */
  w20 = (- w20 );
  /* #96: @18 = (@12*@18) */
  w18  = (w12*w18);
  /* #97: @20 = (@20-@18) */
  w20 -= w18;
  /* #98: @20 = (@20+@21) */
  w20 += w21;
  /* #99: output[0][2] = @20 */
  if (res[0]) res[0][2] = w20;
  /* #100: @20 = sin(@3) */
  w20 = sin( w3 );
  /* #101: @12 = (@12*@13) */
  w12 *= w13;
  /* #102: @12 = (@12*@6) */
  w12 *= w6;
  /* #103: @20 = (@20*@12) */
  w20 *= w12;
  /* #104: @12 = cos(@3) */
  w12 = cos( w3 );
  /* #105: @11 = (@11*@13) */
  w11 *= w13;
  /* #106: @11 = (@11*@6) */
  w11 *= w6;
  /* #107: @12 = (@12*@11) */
  w12 *= w11;
  /* #108: @20 = (@20-@12) */
  w20 -= w12;
  /* #109: @12 = cos(@3) */
  w12 = cos( w3 );
  /* #110: @11 = input[0][6] */
  w11 = arg[0] ? arg[0][6] : 0;
  /* #111: @13 = input[0][7] */
  w13 = arg[0] ? arg[0][7] : 0;
  /* #112: @21 = 4 */
  w21 = 4.;
  /* #113: @18 = (@21*@13) */
  w18  = (w21*w13);
  /* #114: @15 = vertcat(@11, @13, @18) */
  rr=w15;
  *rr++ = w11;
  *rr++ = w13;
  *rr++ = w18;
  /* #115: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #116: @16 = mac(@1,@14,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #117: @15 = (@15-@16) */
  for (i=0, rr=w15, cs=w16; i<3; ++i) (*rr++) -= (*cs++);
  /* #118: @16 = zeros(3x1) */
  casadi_clear(w16, 3);
  /* #119: @1 = @8' */
  for (i=0, rr=w1, cs=w8; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #120: @16 = mac(@1,@14,@16) */
  for (i=0, rr=w16; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #121: @15 = (@15-@16) */
  for (i=0, rr=w15, cs=w16; i<3; ++i) (*rr++) -= (*cs++);
  /* #122: @2 = (@2*@15) */
  for (i=0, rr=w2, cs=w15; i<3; ++i) (*rr++) *= (*cs++);
  /* #123: @2 = @2' */
  /* #124: @2 = (@6*@2) */
  for (i=0, rr=w2, cs=w2; i<3; ++i) (*rr++)  = (w6*(*cs++));
  /* #125: {@6, @11, NULL} = horzsplit(@2) */
  w6 = w2[0];
  w11 = w2[1];
  /* #126: @12 = (@12*@11) */
  w12 *= w11;
  /* #127: @20 = (@20-@12) */
  w20 -= w12;
  /* #128: @12 = sin(@3) */
  w12 = sin( w3 );
  /* #129: @12 = (@12*@6) */
  w12 *= w6;
  /* #130: @20 = (@20-@12) */
  w20 -= w12;
  /* #131: @12 = sin(@3) */
  w12 = sin( w3 );
  /* #132: @1 = zeros(3x3) */
  casadi_clear(w1, 9);
  /* #133: @14 = @14' */
  /* #134: @1 = mac(@10,@14,@1) */
  for (i=0, rr=w1; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w14+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #135: @8 = @1' */
  for (i=0, rr=w8, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #136: {@10, @14, NULL} = horzsplit(@8) */
  casadi_copy(w8, 3, w10);
  casadi_copy(w8+3, 3, w14);
  /* #137: @14 = @14' */
  /* #138: {@6, @11, NULL} = horzsplit(@14) */
  w6 = w14[0];
  w11 = w14[1];
  /* #139: @12 = (@12*@11) */
  w12 *= w11;
  /* #140: @20 = (@20-@12) */
  w20 -= w12;
  /* #141: @12 = cos(@3) */
  w12 = cos( w3 );
  /* #142: @12 = (@12*@6) */
  w12 *= w6;
  /* #143: @20 = (@20+@12) */
  w20 += w12;
  /* #144: @12 = cos(@3) */
  w12 = cos( w3 );
  /* #145: @10 = @10' */
  /* #146: {@6, @11, NULL} = horzsplit(@10) */
  w6 = w10[0];
  w11 = w10[1];
  /* #147: @12 = (@12*@11) */
  w12 *= w11;
  /* #148: @20 = (@20-@12) */
  w20 -= w12;
  /* #149: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #150: @3 = (@3*@6) */
  w3 *= w6;
  /* #151: @20 = (@20-@3) */
  w20 -= w3;
  /* #152: output[0][3] = @20 */
  if (res[0]) res[0][3] = w20;
  /* #153: {@20, @3, @6} = vertsplit(@7) */
  w20 = w7[0];
  w3 = w7[1];
  w6 = w7[2];
  /* #154: output[0][4] = @20 */
  if (res[0]) res[0][4] = w20;
  /* #155: @21 = (@21*@6) */
  w21 *= w6;
  /* #156: @3 = (@3+@21) */
  w3 += w21;
  /* #157: output[0][5] = @3 */
  if (res[0]) res[0][5] = w3;
  /* #158: output[0][6] = @4 */
  if (res[0]) res[0][6] = w4;
  /* #159: output[0][7] = @5 */
  if (res[0]) res[0][7] = w5;
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real simple_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 79;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
