/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) simple_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_project CASADI_PREFIX(project)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_project(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, const casadi_int* sp_y, casadi_real* w) {
  casadi_int ncol_x, ncol_y, i, el;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  for (i=0; i<ncol_x; ++i) {
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) w[row_y[el]] = 0;
    for (el=colind_x[i]; el<colind_x[i+1]; ++el) w[row_x[el]] = x[el];
    for (el=colind_y[i]; el<colind_y[i+1]; ++el) y[el] = w[row_y[el]];
  }
}

static const casadi_int casadi_s0[10] = {3, 3, 0, 1, 2, 4, 2, 2, 0, 1};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[10] = {3, 3, 0, 2, 4, 4, 0, 1, 0, 1};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[8] = {1, 3, 0, 1, 2, 2, 0, 0};
static const casadi_int casadi_s5[7] = {9, 2, 0, 1, 2, 6, 7};
static const casadi_int casadi_s6[14] = {2, 9, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 0, 1};
static const casadi_int casadi_s7[21] = {9, 2, 0, 8, 16, 0, 1, 2, 3, 4, 5, 6, 8, 0, 1, 2, 3, 4, 5, 7, 8};
static const casadi_int casadi_s8[19] = {9, 2, 0, 7, 14, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8};
static const casadi_int casadi_s9[13] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s10[93] = {9, 9, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s11[23] = {9, 2, 0, 9, 18, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8};
static const casadi_int casadi_s12[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s13[3] = {0, 0, 0};
static const casadi_int casadi_s14[75] = {9, 9, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8, 0, 1, 2, 3, 4, 5, 8};

static const casadi_real casadi_c0[3] = {2.5125628140703520e-04, 2.5125628140703520e-04, 5.0753692331117091e-05};
static const casadi_real casadi_c1[9] = {50., 0., 0., 0., 200., 0., 0., 0., 1281.};
static const casadi_real casadi_c2[3] = {0., 0., 1.};

/* simple_model_expl_vde_forw:(i0[9],i1[9x9],i2[9x2],i3[2],i4[])->(o0[9],o1[9x9,63nz],o2[9x2,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+9, w1, w2, w3, w4, *w5=w+16, *w6=w+19, *w7=w+22, *w8=w+31, w9, w10, w11, w12, *w13=w+38, w14, *w15=w+42, w16, w17, *w18=w+47, *w19=w+50, *w20=w+59, w21, *w22=w+69, w23, w24, w25, *w26=w+81, *w27=w+162, *w28=w+171, *w29=w+180, *w30=w+189, *w31=w+198, *w32=w+207, *w33=w+216, *w34=w+225, w35, w36, w37, w38, w39, *w40=w+239, w43, *w44=w+243, *w45=w+245, *w46=w+249, w47, w48, *w49=w+255, w50, w51, w52, w53, w54, w55, *w57=w+263, *w58=w+265, *w59=w+281, *w60=w+299, *w61=w+306, *w62=w+313, *w63=w+327;
  /* #0: @0 = 
  [[0.000251256, 00, 00], 
   [00, 0.000251256, 00], 
   [00, 00, 5.07537e-05]] */
  casadi_copy(casadi_c0, 3, w0);
  /* #1: @0 = nonzeros(@0) */
  /* #2: @1 = input[0][6] */
  w1 = arg[0] ? arg[0][6] : 0;
  /* #3: @2 = input[0][7] */
  w2 = arg[0] ? arg[0][7] : 0;
  /* #4: @3 = 4 */
  w3 = 4.;
  /* #5: @4 = (@3*@2) */
  w4  = (w3*w2);
  /* #6: @5 = vertcat(@1, @2, @4) */
  rr=w5;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w4;
  /* #7: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #8: @7 = 
  [[50, -0, -0], 
   [-0, 200, -0], 
   [-0, -0, 1281]] */
  casadi_copy(casadi_c1, 9, w7);
  /* #9: @1 = input[0][0] */
  w1 = arg[0] ? arg[0][0] : 0;
  /* #10: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #11: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #12: @8 = vertcat(@1, @2, @4) */
  rr=w8;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w4;
  /* #13: @6 = mac(@7,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #14: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #15: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #16: @9 = 0 */
  w9 = 0.;
  /* #17: @10 = 0 */
  w10 = 0.;
  /* #18: @11 = -3980 */
  w11 = -3980.;
  /* #19: @12 = (@11*@2) */
  w12  = (w11*w2);
  /* #20: @13 = horzcat(@9, @10, @12) */
  rr=w13;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w12;
  /* #21: @13 = @13' */
  /* #22: @9 = 0 */
  w9 = 0.;
  /* #23: @10 = 0 */
  w10 = 0.;
  /* #24: @12 = 3980 */
  w12 = 3980.;
  /* #25: @14 = (@12*@1) */
  w14  = (w12*w1);
  /* #26: @15 = horzcat(@9, @10, @14) */
  rr=w15;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w14;
  /* #27: @15 = @15' */
  /* #28: @9 = 3980 */
  w9 = 3980.;
  /* #29: @10 = (@9*@2) */
  w10  = (w9*w2);
  /* #30: @14 = -3980 */
  w14 = -3980.;
  /* #31: @16 = (@14*@1) */
  w16  = (w14*w1);
  /* #32: @17 = 0 */
  w17 = 0.;
  /* #33: @18 = horzcat(@10, @16, @17) */
  rr=w18;
  *rr++ = w10;
  *rr++ = w16;
  *rr++ = w17;
  /* #34: @18 = @18' */
  /* #35: @19 = horzcat(@13, @15, @18) */
  rr=w19;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #36: @20 = @19' */
  for (i=0, rr=w20, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #37: @6 = mac(@20,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #38: @5 = (@5-@6) */
  for (i=0, rr=w5, cs=w6; i<3; ++i) (*rr++) -= (*cs++);
  /* #39: @5 = (@0*@5) */
  for (i=0, rr=w5, cr=w0, cs=w5; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #40: output[0][0] = @5 */
  casadi_copy(w5, 3, res[0]);
  /* #41: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #42: @10 = input[0][5] */
  w10 = arg[0] ? arg[0][5] : 0;
  /* #43: @16 = cos(@10) */
  w16 = cos( w10 );
  /* #44: @17 = sin(@10) */
  w17 = sin( w10 );
  /* #45: @17 = (-@17) */
  w17 = (- w17 );
  /* #46: @21 = 0 */
  w21 = 0.;
  /* #47: @13 = horzcat(@16, @17, @21) */
  rr=w13;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w21;
  /* #48: @13 = @13' */
  /* #49: @16 = sin(@10) */
  w16 = sin( w10 );
  /* #50: @17 = cos(@10) */
  w17 = cos( w10 );
  /* #51: @21 = 0 */
  w21 = 0.;
  /* #52: @15 = horzcat(@16, @17, @21) */
  rr=w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w21;
  /* #53: @15 = @15' */
  /* #54: @18 = [[0, 0, 1]] */
  casadi_copy(casadi_c2, 3, w18);
  /* #55: @18 = @18' */
  /* #56: @19 = horzcat(@13, @15, @18) */
  rr=w19;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  /* #57: @22 = @19' */
  for (i=0, rr=w22, cs=w19; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #58: @6 = mac(@22,@8,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #59: output[0][1] = @6 */
  if (res[0]) casadi_copy(w6, 3, res[0]+3);
  /* #60: @16 = input[3][0] */
  w16 = arg[3] ? arg[3][0] : 0;
  /* #61: output[0][2] = @16 */
  if (res[0]) res[0][6] = w16;
  /* #62: @16 = input[3][1] */
  w16 = arg[3] ? arg[3][1] : 0;
  /* #63: output[0][3] = @16 */
  if (res[0]) res[0][7] = w16;
  /* #64: @16 = 0 */
  w16 = 0.;
  /* #65: @17 = cos(@10) */
  w17 = cos( w10 );
  /* #66: @21 = sin(@10) */
  w21 = sin( w10 );
  /* #67: @21 = (-@21) */
  w21 = (- w21 );
  /* #68: @23 = 0 */
  w23 = 0.;
  /* #69: @6 = horzcat(@17, @21, @23) */
  rr=w6;
  *rr++ = w17;
  *rr++ = w21;
  *rr++ = w23;
  /* #70: @16 = mac(@6,@5,@16) */
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #71: @17 = (@1*@4) */
  w17  = (w1*w4);
  /* #72: @21 = sin(@10) */
  w21 = sin( w10 );
  /* #73: @23 = (@17*@21) */
  w23  = (w17*w21);
  /* #74: @16 = (@16-@23) */
  w16 -= w23;
  /* #75: @23 = (@2*@4) */
  w23  = (w2*w4);
  /* #76: @24 = cos(@10) */
  w24 = cos( w10 );
  /* #77: @25 = (@23*@24) */
  w25  = (w23*w24);
  /* #78: @16 = (@16-@25) */
  w16 -= w25;
  /* #79: output[0][4] = @16 */
  if (res[0]) res[0][8] = w16;
  /* #80: @26 = input[1][0] */
  casadi_copy(arg[1], 81, w26);
  /* #81: {@19, @27, @28, @29, @30, @31, @32, @33, @34} = horzsplit(@26) */
  casadi_copy(w26, 9, w19);
  casadi_copy(w26+9, 9, w27);
  casadi_copy(w26+18, 9, w28);
  casadi_copy(w26+27, 9, w29);
  casadi_copy(w26+36, 9, w30);
  casadi_copy(w26+45, 9, w31);
  casadi_copy(w26+54, 9, w32);
  casadi_copy(w26+63, 9, w33);
  casadi_copy(w26+72, 9, w34);
  /* #82: {@16, @25, @35, NULL, NULL, @36, @37, @38, NULL} = vertsplit(@19) */
  w16 = w19[0];
  w25 = w19[1];
  w35 = w19[2];
  w36 = w19[5];
  w37 = w19[6];
  w38 = w19[7];
  /* #83: @39 = (@3*@38) */
  w39  = (w3*w38);
  /* #84: @13 = vertcat(@37, @38, @39) */
  rr=w13;
  *rr++ = w37;
  *rr++ = w38;
  *rr++ = w39;
  /* #85: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #86: @18 = vertcat(@16, @25, @35) */
  rr=w18;
  *rr++ = w16;
  *rr++ = w25;
  *rr++ = w35;
  /* #87: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #88: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #89: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #90: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #91: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #92: @41 = 00 */
  /* #93: @42 = 00 */
  /* #94: @37 = (@11*@25) */
  w37  = (w11*w25);
  /* #95: @38 = horzcat(@41, @42, @37) */
  rr=(&w38);
  *rr++ = w37;
  /* #96: @38 = @38' */
  /* #97: @41 = 00 */
  /* #98: @42 = 00 */
  /* #99: @37 = (@12*@16) */
  w37  = (w12*w16);
  /* #100: @39 = horzcat(@41, @42, @37) */
  rr=(&w39);
  *rr++ = w37;
  /* #101: @39 = @39' */
  /* #102: @37 = (@9*@25) */
  w37  = (w9*w25);
  /* #103: @43 = (@14*@16) */
  w43  = (w14*w16);
  /* #104: @41 = 00 */
  /* #105: @44 = horzcat(@37, @43, @41) */
  rr=w44;
  *rr++ = w37;
  *rr++ = w43;
  /* #106: @44 = @44' */
  /* #107: @45 = horzcat(@38, @39, @44) */
  rr=w45;
  *rr++ = w38;
  *rr++ = w39;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #108: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #109: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #110: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #111: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #112: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #113: output[1][0] = @13 */
  casadi_copy(w13, 3, res[1]);
  /* #114: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #115: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #116: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #117: @38 = sin(@10) */
  w38 = sin( w10 );
  /* #118: @39 = (@38*@36) */
  w39  = (w38*w36);
  /* #119: @39 = (-@39) */
  w39 = (- w39 );
  /* #120: @37 = cos(@10) */
  w37 = cos( w10 );
  /* #121: @43 = (@37*@36) */
  w43  = (w37*w36);
  /* #122: @43 = (-@43) */
  w43 = (- w43 );
  /* #123: @41 = 00 */
  /* #124: @44 = horzcat(@39, @43, @41) */
  rr=w44;
  *rr++ = w39;
  *rr++ = w43;
  /* #125: @44 = @44' */
  /* #126: @39 = cos(@10) */
  w39 = cos( w10 );
  /* #127: @43 = (@39*@36) */
  w43  = (w39*w36);
  /* #128: @47 = sin(@10) */
  w47 = sin( w10 );
  /* #129: @48 = (@47*@36) */
  w48  = (w47*w36);
  /* #130: @48 = (-@48) */
  w48 = (- w48 );
  /* #131: @41 = 00 */
  /* #132: @49 = horzcat(@43, @48, @41) */
  rr=w49;
  *rr++ = w43;
  *rr++ = w48;
  /* #133: @49 = @49' */
  /* #134: @41 = zeros(3x1,0nz) */
  /* #135: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #136: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #137: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #138: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #139: output[1][1] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+3);
  /* #140: @43 = 0 */
  w43 = 0.;
  /* #141: @43 = mac(@6,@13,@43) */
  for (i=0, rr=(&w43); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #142: @48 = 0 */
  w48 = 0.;
  /* #143: @50 = sin(@10) */
  w50 = sin( w10 );
  /* #144: @51 = (@50*@36) */
  w51  = (w50*w36);
  /* #145: @51 = (-@51) */
  w51 = (- w51 );
  /* #146: @52 = cos(@10) */
  w52 = cos( w10 );
  /* #147: @53 = (@52*@36) */
  w53  = (w52*w36);
  /* #148: @53 = (-@53) */
  w53 = (- w53 );
  /* #149: @41 = 00 */
  /* #150: @44 = horzcat(@51, @53, @41) */
  rr=w44;
  *rr++ = w51;
  *rr++ = w53;
  /* #151: @48 = mac(@44,@5,@48) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w48), casadi_s3, w, 0);
  /* #152: @43 = (@43+@48) */
  w43 += w48;
  /* #153: @16 = (@4*@16) */
  w16  = (w4*w16);
  /* #154: @48 = (@1*@35) */
  w48  = (w1*w35);
  /* #155: @16 = (@16+@48) */
  w16 += w48;
  /* #156: @16 = (@21*@16) */
  w16  = (w21*w16);
  /* #157: @48 = cos(@10) */
  w48 = cos( w10 );
  /* #158: @51 = (@48*@36) */
  w51  = (w48*w36);
  /* #159: @51 = (@17*@51) */
  w51  = (w17*w51);
  /* #160: @16 = (@16+@51) */
  w16 += w51;
  /* #161: @43 = (@43-@16) */
  w43 -= w16;
  /* #162: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #163: @35 = (@2*@35) */
  w35  = (w2*w35);
  /* #164: @25 = (@25+@35) */
  w25 += w35;
  /* #165: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #166: @35 = sin(@10) */
  w35 = sin( w10 );
  /* #167: @36 = (@35*@36) */
  w36  = (w35*w36);
  /* #168: @36 = (@23*@36) */
  w36  = (w23*w36);
  /* #169: @25 = (@25-@36) */
  w25 -= w36;
  /* #170: @43 = (@43-@25) */
  w43 -= w25;
  /* #171: output[1][2] = @43 */
  if (res[1]) res[1][6] = w43;
  /* #172: {@43, @25, @36, NULL, NULL, @16, @51, @53, NULL} = vertsplit(@27) */
  w43 = w27[0];
  w25 = w27[1];
  w36 = w27[2];
  w16 = w27[5];
  w51 = w27[6];
  w53 = w27[7];
  /* #173: @54 = (@3*@53) */
  w54  = (w3*w53);
  /* #174: @13 = vertcat(@51, @53, @54) */
  rr=w13;
  *rr++ = w51;
  *rr++ = w53;
  *rr++ = w54;
  /* #175: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #176: @18 = vertcat(@43, @25, @36) */
  rr=w18;
  *rr++ = w43;
  *rr++ = w25;
  *rr++ = w36;
  /* #177: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #178: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #179: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #180: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #181: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #182: @41 = 00 */
  /* #183: @42 = 00 */
  /* #184: @51 = (@11*@25) */
  w51  = (w11*w25);
  /* #185: @53 = horzcat(@41, @42, @51) */
  rr=(&w53);
  *rr++ = w51;
  /* #186: @53 = @53' */
  /* #187: @41 = 00 */
  /* #188: @42 = 00 */
  /* #189: @51 = (@12*@43) */
  w51  = (w12*w43);
  /* #190: @54 = horzcat(@41, @42, @51) */
  rr=(&w54);
  *rr++ = w51;
  /* #191: @54 = @54' */
  /* #192: @51 = (@9*@25) */
  w51  = (w9*w25);
  /* #193: @55 = (@14*@43) */
  w55  = (w14*w43);
  /* #194: @41 = 00 */
  /* #195: @44 = horzcat(@51, @55, @41) */
  rr=w44;
  *rr++ = w51;
  *rr++ = w55;
  /* #196: @44 = @44' */
  /* #197: @45 = horzcat(@53, @54, @44) */
  rr=w45;
  *rr++ = w53;
  *rr++ = w54;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #198: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #199: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #200: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #201: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #202: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #203: output[1][3] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+7);
  /* #204: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #205: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #206: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #207: @53 = (@38*@16) */
  w53  = (w38*w16);
  /* #208: @53 = (-@53) */
  w53 = (- w53 );
  /* #209: @54 = (@37*@16) */
  w54  = (w37*w16);
  /* #210: @54 = (-@54) */
  w54 = (- w54 );
  /* #211: @41 = 00 */
  /* #212: @44 = horzcat(@53, @54, @41) */
  rr=w44;
  *rr++ = w53;
  *rr++ = w54;
  /* #213: @44 = @44' */
  /* #214: @53 = (@39*@16) */
  w53  = (w39*w16);
  /* #215: @54 = (@47*@16) */
  w54  = (w47*w16);
  /* #216: @54 = (-@54) */
  w54 = (- w54 );
  /* #217: @41 = 00 */
  /* #218: @49 = horzcat(@53, @54, @41) */
  rr=w49;
  *rr++ = w53;
  *rr++ = w54;
  /* #219: @49 = @49' */
  /* #220: @41 = zeros(3x1,0nz) */
  /* #221: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #222: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #223: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #224: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #225: output[1][4] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+10);
  /* #226: @53 = 0 */
  w53 = 0.;
  /* #227: @53 = mac(@6,@13,@53) */
  for (i=0, rr=(&w53); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #228: @54 = 0 */
  w54 = 0.;
  /* #229: @51 = (@50*@16) */
  w51  = (w50*w16);
  /* #230: @51 = (-@51) */
  w51 = (- w51 );
  /* #231: @55 = (@52*@16) */
  w55  = (w52*w16);
  /* #232: @55 = (-@55) */
  w55 = (- w55 );
  /* #233: @41 = 00 */
  /* #234: @44 = horzcat(@51, @55, @41) */
  rr=w44;
  *rr++ = w51;
  *rr++ = w55;
  /* #235: @54 = mac(@44,@5,@54) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w54), casadi_s3, w, 0);
  /* #236: @53 = (@53+@54) */
  w53 += w54;
  /* #237: @43 = (@4*@43) */
  w43  = (w4*w43);
  /* #238: @54 = (@1*@36) */
  w54  = (w1*w36);
  /* #239: @43 = (@43+@54) */
  w43 += w54;
  /* #240: @43 = (@21*@43) */
  w43  = (w21*w43);
  /* #241: @54 = (@48*@16) */
  w54  = (w48*w16);
  /* #242: @54 = (@17*@54) */
  w54  = (w17*w54);
  /* #243: @43 = (@43+@54) */
  w43 += w54;
  /* #244: @53 = (@53-@43) */
  w53 -= w43;
  /* #245: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #246: @36 = (@2*@36) */
  w36  = (w2*w36);
  /* #247: @25 = (@25+@36) */
  w25 += w36;
  /* #248: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #249: @16 = (@35*@16) */
  w16  = (w35*w16);
  /* #250: @16 = (@23*@16) */
  w16  = (w23*w16);
  /* #251: @25 = (@25-@16) */
  w25 -= w16;
  /* #252: @53 = (@53-@25) */
  w53 -= w25;
  /* #253: output[1][5] = @53 */
  if (res[1]) res[1][13] = w53;
  /* #254: {@53, @25, @16, NULL, NULL, @36, @43, @54, NULL} = vertsplit(@28) */
  w53 = w28[0];
  w25 = w28[1];
  w16 = w28[2];
  w36 = w28[5];
  w43 = w28[6];
  w54 = w28[7];
  /* #255: @51 = (@3*@54) */
  w51  = (w3*w54);
  /* #256: @13 = vertcat(@43, @54, @51) */
  rr=w13;
  *rr++ = w43;
  *rr++ = w54;
  *rr++ = w51;
  /* #257: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #258: @18 = vertcat(@53, @25, @16) */
  rr=w18;
  *rr++ = w53;
  *rr++ = w25;
  *rr++ = w16;
  /* #259: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #260: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #261: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #262: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #263: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #264: @41 = 00 */
  /* #265: @42 = 00 */
  /* #266: @43 = (@11*@25) */
  w43  = (w11*w25);
  /* #267: @54 = horzcat(@41, @42, @43) */
  rr=(&w54);
  *rr++ = w43;
  /* #268: @54 = @54' */
  /* #269: @41 = 00 */
  /* #270: @42 = 00 */
  /* #271: @43 = (@12*@53) */
  w43  = (w12*w53);
  /* #272: @51 = horzcat(@41, @42, @43) */
  rr=(&w51);
  *rr++ = w43;
  /* #273: @51 = @51' */
  /* #274: @43 = (@9*@25) */
  w43  = (w9*w25);
  /* #275: @55 = (@14*@53) */
  w55  = (w14*w53);
  /* #276: @41 = 00 */
  /* #277: @44 = horzcat(@43, @55, @41) */
  rr=w44;
  *rr++ = w43;
  *rr++ = w55;
  /* #278: @44 = @44' */
  /* #279: @45 = horzcat(@54, @51, @44) */
  rr=w45;
  *rr++ = w54;
  *rr++ = w51;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #280: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #281: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #282: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #283: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #284: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #285: output[1][6] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+14);
  /* #286: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #287: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #288: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #289: @54 = (@38*@36) */
  w54  = (w38*w36);
  /* #290: @54 = (-@54) */
  w54 = (- w54 );
  /* #291: @51 = (@37*@36) */
  w51  = (w37*w36);
  /* #292: @51 = (-@51) */
  w51 = (- w51 );
  /* #293: @41 = 00 */
  /* #294: @44 = horzcat(@54, @51, @41) */
  rr=w44;
  *rr++ = w54;
  *rr++ = w51;
  /* #295: @44 = @44' */
  /* #296: @54 = (@39*@36) */
  w54  = (w39*w36);
  /* #297: @51 = (@47*@36) */
  w51  = (w47*w36);
  /* #298: @51 = (-@51) */
  w51 = (- w51 );
  /* #299: @41 = 00 */
  /* #300: @49 = horzcat(@54, @51, @41) */
  rr=w49;
  *rr++ = w54;
  *rr++ = w51;
  /* #301: @49 = @49' */
  /* #302: @41 = zeros(3x1,0nz) */
  /* #303: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #304: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #305: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #306: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #307: output[1][7] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+17);
  /* #308: @54 = 0 */
  w54 = 0.;
  /* #309: @54 = mac(@6,@13,@54) */
  for (i=0, rr=(&w54); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #310: @51 = 0 */
  w51 = 0.;
  /* #311: @43 = (@50*@36) */
  w43  = (w50*w36);
  /* #312: @43 = (-@43) */
  w43 = (- w43 );
  /* #313: @55 = (@52*@36) */
  w55  = (w52*w36);
  /* #314: @55 = (-@55) */
  w55 = (- w55 );
  /* #315: @41 = 00 */
  /* #316: @44 = horzcat(@43, @55, @41) */
  rr=w44;
  *rr++ = w43;
  *rr++ = w55;
  /* #317: @51 = mac(@44,@5,@51) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w51), casadi_s3, w, 0);
  /* #318: @54 = (@54+@51) */
  w54 += w51;
  /* #319: @53 = (@4*@53) */
  w53  = (w4*w53);
  /* #320: @51 = (@1*@16) */
  w51  = (w1*w16);
  /* #321: @53 = (@53+@51) */
  w53 += w51;
  /* #322: @53 = (@21*@53) */
  w53  = (w21*w53);
  /* #323: @51 = (@48*@36) */
  w51  = (w48*w36);
  /* #324: @51 = (@17*@51) */
  w51  = (w17*w51);
  /* #325: @53 = (@53+@51) */
  w53 += w51;
  /* #326: @54 = (@54-@53) */
  w54 -= w53;
  /* #327: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #328: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #329: @25 = (@25+@16) */
  w25 += w16;
  /* #330: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #331: @36 = (@35*@36) */
  w36  = (w35*w36);
  /* #332: @36 = (@23*@36) */
  w36  = (w23*w36);
  /* #333: @25 = (@25-@36) */
  w25 -= w36;
  /* #334: @54 = (@54-@25) */
  w54 -= w25;
  /* #335: output[1][8] = @54 */
  if (res[1]) res[1][20] = w54;
  /* #336: {@54, @25, @36, NULL, NULL, @16, @53, @51, NULL} = vertsplit(@29) */
  w54 = w29[0];
  w25 = w29[1];
  w36 = w29[2];
  w16 = w29[5];
  w53 = w29[6];
  w51 = w29[7];
  /* #337: @43 = (@3*@51) */
  w43  = (w3*w51);
  /* #338: @13 = vertcat(@53, @51, @43) */
  rr=w13;
  *rr++ = w53;
  *rr++ = w51;
  *rr++ = w43;
  /* #339: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #340: @18 = vertcat(@54, @25, @36) */
  rr=w18;
  *rr++ = w54;
  *rr++ = w25;
  *rr++ = w36;
  /* #341: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #342: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #343: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #344: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #345: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #346: @41 = 00 */
  /* #347: @42 = 00 */
  /* #348: @53 = (@11*@25) */
  w53  = (w11*w25);
  /* #349: @51 = horzcat(@41, @42, @53) */
  rr=(&w51);
  *rr++ = w53;
  /* #350: @51 = @51' */
  /* #351: @41 = 00 */
  /* #352: @42 = 00 */
  /* #353: @53 = (@12*@54) */
  w53  = (w12*w54);
  /* #354: @43 = horzcat(@41, @42, @53) */
  rr=(&w43);
  *rr++ = w53;
  /* #355: @43 = @43' */
  /* #356: @53 = (@9*@25) */
  w53  = (w9*w25);
  /* #357: @55 = (@14*@54) */
  w55  = (w14*w54);
  /* #358: @41 = 00 */
  /* #359: @44 = horzcat(@53, @55, @41) */
  rr=w44;
  *rr++ = w53;
  *rr++ = w55;
  /* #360: @44 = @44' */
  /* #361: @45 = horzcat(@51, @43, @44) */
  rr=w45;
  *rr++ = w51;
  *rr++ = w43;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #362: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #363: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #364: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #365: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #366: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #367: output[1][9] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+21);
  /* #368: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #369: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #370: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #371: @51 = (@38*@16) */
  w51  = (w38*w16);
  /* #372: @51 = (-@51) */
  w51 = (- w51 );
  /* #373: @43 = (@37*@16) */
  w43  = (w37*w16);
  /* #374: @43 = (-@43) */
  w43 = (- w43 );
  /* #375: @41 = 00 */
  /* #376: @44 = horzcat(@51, @43, @41) */
  rr=w44;
  *rr++ = w51;
  *rr++ = w43;
  /* #377: @44 = @44' */
  /* #378: @51 = (@39*@16) */
  w51  = (w39*w16);
  /* #379: @43 = (@47*@16) */
  w43  = (w47*w16);
  /* #380: @43 = (-@43) */
  w43 = (- w43 );
  /* #381: @41 = 00 */
  /* #382: @49 = horzcat(@51, @43, @41) */
  rr=w49;
  *rr++ = w51;
  *rr++ = w43;
  /* #383: @49 = @49' */
  /* #384: @41 = zeros(3x1,0nz) */
  /* #385: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #386: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #387: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #388: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #389: output[1][10] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+24);
  /* #390: @51 = 0 */
  w51 = 0.;
  /* #391: @51 = mac(@6,@13,@51) */
  for (i=0, rr=(&w51); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #392: @43 = 0 */
  w43 = 0.;
  /* #393: @53 = (@50*@16) */
  w53  = (w50*w16);
  /* #394: @53 = (-@53) */
  w53 = (- w53 );
  /* #395: @55 = (@52*@16) */
  w55  = (w52*w16);
  /* #396: @55 = (-@55) */
  w55 = (- w55 );
  /* #397: @41 = 00 */
  /* #398: @44 = horzcat(@53, @55, @41) */
  rr=w44;
  *rr++ = w53;
  *rr++ = w55;
  /* #399: @43 = mac(@44,@5,@43) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w43), casadi_s3, w, 0);
  /* #400: @51 = (@51+@43) */
  w51 += w43;
  /* #401: @54 = (@4*@54) */
  w54  = (w4*w54);
  /* #402: @43 = (@1*@36) */
  w43  = (w1*w36);
  /* #403: @54 = (@54+@43) */
  w54 += w43;
  /* #404: @54 = (@21*@54) */
  w54  = (w21*w54);
  /* #405: @43 = (@48*@16) */
  w43  = (w48*w16);
  /* #406: @43 = (@17*@43) */
  w43  = (w17*w43);
  /* #407: @54 = (@54+@43) */
  w54 += w43;
  /* #408: @51 = (@51-@54) */
  w51 -= w54;
  /* #409: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #410: @36 = (@2*@36) */
  w36  = (w2*w36);
  /* #411: @25 = (@25+@36) */
  w25 += w36;
  /* #412: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #413: @16 = (@35*@16) */
  w16  = (w35*w16);
  /* #414: @16 = (@23*@16) */
  w16  = (w23*w16);
  /* #415: @25 = (@25-@16) */
  w25 -= w16;
  /* #416: @51 = (@51-@25) */
  w51 -= w25;
  /* #417: output[1][11] = @51 */
  if (res[1]) res[1][27] = w51;
  /* #418: {@51, @25, @16, NULL, NULL, @36, @54, @43, NULL} = vertsplit(@30) */
  w51 = w30[0];
  w25 = w30[1];
  w16 = w30[2];
  w36 = w30[5];
  w54 = w30[6];
  w43 = w30[7];
  /* #419: @53 = (@3*@43) */
  w53  = (w3*w43);
  /* #420: @13 = vertcat(@54, @43, @53) */
  rr=w13;
  *rr++ = w54;
  *rr++ = w43;
  *rr++ = w53;
  /* #421: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #422: @18 = vertcat(@51, @25, @16) */
  rr=w18;
  *rr++ = w51;
  *rr++ = w25;
  *rr++ = w16;
  /* #423: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #424: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #425: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #426: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #427: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #428: @41 = 00 */
  /* #429: @42 = 00 */
  /* #430: @54 = (@11*@25) */
  w54  = (w11*w25);
  /* #431: @43 = horzcat(@41, @42, @54) */
  rr=(&w43);
  *rr++ = w54;
  /* #432: @43 = @43' */
  /* #433: @41 = 00 */
  /* #434: @42 = 00 */
  /* #435: @54 = (@12*@51) */
  w54  = (w12*w51);
  /* #436: @53 = horzcat(@41, @42, @54) */
  rr=(&w53);
  *rr++ = w54;
  /* #437: @53 = @53' */
  /* #438: @54 = (@9*@25) */
  w54  = (w9*w25);
  /* #439: @55 = (@14*@51) */
  w55  = (w14*w51);
  /* #440: @41 = 00 */
  /* #441: @44 = horzcat(@54, @55, @41) */
  rr=w44;
  *rr++ = w54;
  *rr++ = w55;
  /* #442: @44 = @44' */
  /* #443: @45 = horzcat(@43, @53, @44) */
  rr=w45;
  *rr++ = w43;
  *rr++ = w53;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #444: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #445: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #446: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #447: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #448: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #449: output[1][12] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+28);
  /* #450: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #451: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #452: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #453: @43 = (@38*@36) */
  w43  = (w38*w36);
  /* #454: @43 = (-@43) */
  w43 = (- w43 );
  /* #455: @53 = (@37*@36) */
  w53  = (w37*w36);
  /* #456: @53 = (-@53) */
  w53 = (- w53 );
  /* #457: @41 = 00 */
  /* #458: @44 = horzcat(@43, @53, @41) */
  rr=w44;
  *rr++ = w43;
  *rr++ = w53;
  /* #459: @44 = @44' */
  /* #460: @43 = (@39*@36) */
  w43  = (w39*w36);
  /* #461: @53 = (@47*@36) */
  w53  = (w47*w36);
  /* #462: @53 = (-@53) */
  w53 = (- w53 );
  /* #463: @41 = 00 */
  /* #464: @49 = horzcat(@43, @53, @41) */
  rr=w49;
  *rr++ = w43;
  *rr++ = w53;
  /* #465: @49 = @49' */
  /* #466: @41 = zeros(3x1,0nz) */
  /* #467: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #468: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #469: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #470: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #471: output[1][13] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+31);
  /* #472: @43 = 0 */
  w43 = 0.;
  /* #473: @43 = mac(@6,@13,@43) */
  for (i=0, rr=(&w43); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #474: @53 = 0 */
  w53 = 0.;
  /* #475: @54 = (@50*@36) */
  w54  = (w50*w36);
  /* #476: @54 = (-@54) */
  w54 = (- w54 );
  /* #477: @55 = (@52*@36) */
  w55  = (w52*w36);
  /* #478: @55 = (-@55) */
  w55 = (- w55 );
  /* #479: @41 = 00 */
  /* #480: @44 = horzcat(@54, @55, @41) */
  rr=w44;
  *rr++ = w54;
  *rr++ = w55;
  /* #481: @53 = mac(@44,@5,@53) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w53), casadi_s3, w, 0);
  /* #482: @43 = (@43+@53) */
  w43 += w53;
  /* #483: @51 = (@4*@51) */
  w51  = (w4*w51);
  /* #484: @53 = (@1*@16) */
  w53  = (w1*w16);
  /* #485: @51 = (@51+@53) */
  w51 += w53;
  /* #486: @51 = (@21*@51) */
  w51  = (w21*w51);
  /* #487: @53 = (@48*@36) */
  w53  = (w48*w36);
  /* #488: @53 = (@17*@53) */
  w53  = (w17*w53);
  /* #489: @51 = (@51+@53) */
  w51 += w53;
  /* #490: @43 = (@43-@51) */
  w43 -= w51;
  /* #491: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #492: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #493: @25 = (@25+@16) */
  w25 += w16;
  /* #494: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #495: @36 = (@35*@36) */
  w36  = (w35*w36);
  /* #496: @36 = (@23*@36) */
  w36  = (w23*w36);
  /* #497: @25 = (@25-@36) */
  w25 -= w36;
  /* #498: @43 = (@43-@25) */
  w43 -= w25;
  /* #499: output[1][14] = @43 */
  if (res[1]) res[1][34] = w43;
  /* #500: {@43, @25, @36, NULL, NULL, @16, @51, @53, NULL} = vertsplit(@31) */
  w43 = w31[0];
  w25 = w31[1];
  w36 = w31[2];
  w16 = w31[5];
  w51 = w31[6];
  w53 = w31[7];
  /* #501: @54 = (@3*@53) */
  w54  = (w3*w53);
  /* #502: @13 = vertcat(@51, @53, @54) */
  rr=w13;
  *rr++ = w51;
  *rr++ = w53;
  *rr++ = w54;
  /* #503: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #504: @18 = vertcat(@43, @25, @36) */
  rr=w18;
  *rr++ = w43;
  *rr++ = w25;
  *rr++ = w36;
  /* #505: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #506: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #507: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #508: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #509: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #510: @41 = 00 */
  /* #511: @42 = 00 */
  /* #512: @51 = (@11*@25) */
  w51  = (w11*w25);
  /* #513: @53 = horzcat(@41, @42, @51) */
  rr=(&w53);
  *rr++ = w51;
  /* #514: @53 = @53' */
  /* #515: @41 = 00 */
  /* #516: @42 = 00 */
  /* #517: @51 = (@12*@43) */
  w51  = (w12*w43);
  /* #518: @54 = horzcat(@41, @42, @51) */
  rr=(&w54);
  *rr++ = w51;
  /* #519: @54 = @54' */
  /* #520: @51 = (@9*@25) */
  w51  = (w9*w25);
  /* #521: @55 = (@14*@43) */
  w55  = (w14*w43);
  /* #522: @41 = 00 */
  /* #523: @44 = horzcat(@51, @55, @41) */
  rr=w44;
  *rr++ = w51;
  *rr++ = w55;
  /* #524: @44 = @44' */
  /* #525: @45 = horzcat(@53, @54, @44) */
  rr=w45;
  *rr++ = w53;
  *rr++ = w54;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #526: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #527: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #528: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #529: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #530: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #531: output[1][15] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+35);
  /* #532: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #533: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #534: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #535: @53 = (@38*@16) */
  w53  = (w38*w16);
  /* #536: @53 = (-@53) */
  w53 = (- w53 );
  /* #537: @54 = (@37*@16) */
  w54  = (w37*w16);
  /* #538: @54 = (-@54) */
  w54 = (- w54 );
  /* #539: @41 = 00 */
  /* #540: @44 = horzcat(@53, @54, @41) */
  rr=w44;
  *rr++ = w53;
  *rr++ = w54;
  /* #541: @44 = @44' */
  /* #542: @53 = (@39*@16) */
  w53  = (w39*w16);
  /* #543: @54 = (@47*@16) */
  w54  = (w47*w16);
  /* #544: @54 = (-@54) */
  w54 = (- w54 );
  /* #545: @41 = 00 */
  /* #546: @49 = horzcat(@53, @54, @41) */
  rr=w49;
  *rr++ = w53;
  *rr++ = w54;
  /* #547: @49 = @49' */
  /* #548: @41 = zeros(3x1,0nz) */
  /* #549: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #550: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #551: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #552: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #553: output[1][16] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+38);
  /* #554: @53 = 0 */
  w53 = 0.;
  /* #555: @53 = mac(@6,@13,@53) */
  for (i=0, rr=(&w53); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #556: @54 = 0 */
  w54 = 0.;
  /* #557: @51 = (@50*@16) */
  w51  = (w50*w16);
  /* #558: @51 = (-@51) */
  w51 = (- w51 );
  /* #559: @55 = (@52*@16) */
  w55  = (w52*w16);
  /* #560: @55 = (-@55) */
  w55 = (- w55 );
  /* #561: @41 = 00 */
  /* #562: @44 = horzcat(@51, @55, @41) */
  rr=w44;
  *rr++ = w51;
  *rr++ = w55;
  /* #563: @54 = mac(@44,@5,@54) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w54), casadi_s3, w, 0);
  /* #564: @53 = (@53+@54) */
  w53 += w54;
  /* #565: @43 = (@4*@43) */
  w43  = (w4*w43);
  /* #566: @54 = (@1*@36) */
  w54  = (w1*w36);
  /* #567: @43 = (@43+@54) */
  w43 += w54;
  /* #568: @43 = (@21*@43) */
  w43  = (w21*w43);
  /* #569: @54 = (@48*@16) */
  w54  = (w48*w16);
  /* #570: @54 = (@17*@54) */
  w54  = (w17*w54);
  /* #571: @43 = (@43+@54) */
  w43 += w54;
  /* #572: @53 = (@53-@43) */
  w53 -= w43;
  /* #573: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #574: @36 = (@2*@36) */
  w36  = (w2*w36);
  /* #575: @25 = (@25+@36) */
  w25 += w36;
  /* #576: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #577: @16 = (@35*@16) */
  w16  = (w35*w16);
  /* #578: @16 = (@23*@16) */
  w16  = (w23*w16);
  /* #579: @25 = (@25-@16) */
  w25 -= w16;
  /* #580: @53 = (@53-@25) */
  w53 -= w25;
  /* #581: output[1][17] = @53 */
  if (res[1]) res[1][41] = w53;
  /* #582: {@53, @25, @16, NULL, NULL, @36, @43, @54, NULL} = vertsplit(@32) */
  w53 = w32[0];
  w25 = w32[1];
  w16 = w32[2];
  w36 = w32[5];
  w43 = w32[6];
  w54 = w32[7];
  /* #583: @51 = (@3*@54) */
  w51  = (w3*w54);
  /* #584: @13 = vertcat(@43, @54, @51) */
  rr=w13;
  *rr++ = w43;
  *rr++ = w54;
  *rr++ = w51;
  /* #585: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #586: @18 = vertcat(@53, @25, @16) */
  rr=w18;
  *rr++ = w53;
  *rr++ = w25;
  *rr++ = w16;
  /* #587: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #588: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #589: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #590: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #591: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #592: @41 = 00 */
  /* #593: @42 = 00 */
  /* #594: @43 = (@11*@25) */
  w43  = (w11*w25);
  /* #595: @54 = horzcat(@41, @42, @43) */
  rr=(&w54);
  *rr++ = w43;
  /* #596: @54 = @54' */
  /* #597: @41 = 00 */
  /* #598: @42 = 00 */
  /* #599: @43 = (@12*@53) */
  w43  = (w12*w53);
  /* #600: @51 = horzcat(@41, @42, @43) */
  rr=(&w51);
  *rr++ = w43;
  /* #601: @51 = @51' */
  /* #602: @43 = (@9*@25) */
  w43  = (w9*w25);
  /* #603: @55 = (@14*@53) */
  w55  = (w14*w53);
  /* #604: @41 = 00 */
  /* #605: @44 = horzcat(@43, @55, @41) */
  rr=w44;
  *rr++ = w43;
  *rr++ = w55;
  /* #606: @44 = @44' */
  /* #607: @45 = horzcat(@54, @51, @44) */
  rr=w45;
  *rr++ = w54;
  *rr++ = w51;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #608: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #609: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #610: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #611: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #612: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #613: output[1][18] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+42);
  /* #614: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #615: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #616: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #617: @54 = (@38*@36) */
  w54  = (w38*w36);
  /* #618: @54 = (-@54) */
  w54 = (- w54 );
  /* #619: @51 = (@37*@36) */
  w51  = (w37*w36);
  /* #620: @51 = (-@51) */
  w51 = (- w51 );
  /* #621: @41 = 00 */
  /* #622: @44 = horzcat(@54, @51, @41) */
  rr=w44;
  *rr++ = w54;
  *rr++ = w51;
  /* #623: @44 = @44' */
  /* #624: @54 = (@39*@36) */
  w54  = (w39*w36);
  /* #625: @51 = (@47*@36) */
  w51  = (w47*w36);
  /* #626: @51 = (-@51) */
  w51 = (- w51 );
  /* #627: @41 = 00 */
  /* #628: @49 = horzcat(@54, @51, @41) */
  rr=w49;
  *rr++ = w54;
  *rr++ = w51;
  /* #629: @49 = @49' */
  /* #630: @41 = zeros(3x1,0nz) */
  /* #631: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #632: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #633: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #634: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #635: output[1][19] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+45);
  /* #636: @54 = 0 */
  w54 = 0.;
  /* #637: @54 = mac(@6,@13,@54) */
  for (i=0, rr=(&w54); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #638: @51 = 0 */
  w51 = 0.;
  /* #639: @43 = (@50*@36) */
  w43  = (w50*w36);
  /* #640: @43 = (-@43) */
  w43 = (- w43 );
  /* #641: @55 = (@52*@36) */
  w55  = (w52*w36);
  /* #642: @55 = (-@55) */
  w55 = (- w55 );
  /* #643: @41 = 00 */
  /* #644: @44 = horzcat(@43, @55, @41) */
  rr=w44;
  *rr++ = w43;
  *rr++ = w55;
  /* #645: @51 = mac(@44,@5,@51) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w51), casadi_s3, w, 0);
  /* #646: @54 = (@54+@51) */
  w54 += w51;
  /* #647: @53 = (@4*@53) */
  w53  = (w4*w53);
  /* #648: @51 = (@1*@16) */
  w51  = (w1*w16);
  /* #649: @53 = (@53+@51) */
  w53 += w51;
  /* #650: @53 = (@21*@53) */
  w53  = (w21*w53);
  /* #651: @51 = (@48*@36) */
  w51  = (w48*w36);
  /* #652: @51 = (@17*@51) */
  w51  = (w17*w51);
  /* #653: @53 = (@53+@51) */
  w53 += w51;
  /* #654: @54 = (@54-@53) */
  w54 -= w53;
  /* #655: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #656: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #657: @25 = (@25+@16) */
  w25 += w16;
  /* #658: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #659: @36 = (@35*@36) */
  w36  = (w35*w36);
  /* #660: @36 = (@23*@36) */
  w36  = (w23*w36);
  /* #661: @25 = (@25-@36) */
  w25 -= w36;
  /* #662: @54 = (@54-@25) */
  w54 -= w25;
  /* #663: output[1][20] = @54 */
  if (res[1]) res[1][48] = w54;
  /* #664: {@54, @25, @36, NULL, NULL, @16, @53, @51, NULL} = vertsplit(@33) */
  w54 = w33[0];
  w25 = w33[1];
  w36 = w33[2];
  w16 = w33[5];
  w53 = w33[6];
  w51 = w33[7];
  /* #665: @43 = (@3*@51) */
  w43  = (w3*w51);
  /* #666: @13 = vertcat(@53, @51, @43) */
  rr=w13;
  *rr++ = w53;
  *rr++ = w51;
  *rr++ = w43;
  /* #667: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #668: @18 = vertcat(@54, @25, @36) */
  rr=w18;
  *rr++ = w54;
  *rr++ = w25;
  *rr++ = w36;
  /* #669: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #670: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #671: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #672: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #673: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #674: @41 = 00 */
  /* #675: @42 = 00 */
  /* #676: @53 = (@11*@25) */
  w53  = (w11*w25);
  /* #677: @51 = horzcat(@41, @42, @53) */
  rr=(&w51);
  *rr++ = w53;
  /* #678: @51 = @51' */
  /* #679: @41 = 00 */
  /* #680: @42 = 00 */
  /* #681: @53 = (@12*@54) */
  w53  = (w12*w54);
  /* #682: @43 = horzcat(@41, @42, @53) */
  rr=(&w43);
  *rr++ = w53;
  /* #683: @43 = @43' */
  /* #684: @53 = (@9*@25) */
  w53  = (w9*w25);
  /* #685: @55 = (@14*@54) */
  w55  = (w14*w54);
  /* #686: @41 = 00 */
  /* #687: @44 = horzcat(@53, @55, @41) */
  rr=w44;
  *rr++ = w53;
  *rr++ = w55;
  /* #688: @44 = @44' */
  /* #689: @45 = horzcat(@51, @43, @44) */
  rr=w45;
  *rr++ = w51;
  *rr++ = w43;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #690: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #691: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #692: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #693: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #694: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #695: output[1][21] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+49);
  /* #696: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #697: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #698: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #699: @51 = (@38*@16) */
  w51  = (w38*w16);
  /* #700: @51 = (-@51) */
  w51 = (- w51 );
  /* #701: @43 = (@37*@16) */
  w43  = (w37*w16);
  /* #702: @43 = (-@43) */
  w43 = (- w43 );
  /* #703: @41 = 00 */
  /* #704: @44 = horzcat(@51, @43, @41) */
  rr=w44;
  *rr++ = w51;
  *rr++ = w43;
  /* #705: @44 = @44' */
  /* #706: @51 = (@39*@16) */
  w51  = (w39*w16);
  /* #707: @43 = (@47*@16) */
  w43  = (w47*w16);
  /* #708: @43 = (-@43) */
  w43 = (- w43 );
  /* #709: @41 = 00 */
  /* #710: @49 = horzcat(@51, @43, @41) */
  rr=w49;
  *rr++ = w51;
  *rr++ = w43;
  /* #711: @49 = @49' */
  /* #712: @41 = zeros(3x1,0nz) */
  /* #713: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #714: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #715: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #716: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #717: output[1][22] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+52);
  /* #718: @51 = 0 */
  w51 = 0.;
  /* #719: @51 = mac(@6,@13,@51) */
  for (i=0, rr=(&w51); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #720: @43 = 0 */
  w43 = 0.;
  /* #721: @53 = (@50*@16) */
  w53  = (w50*w16);
  /* #722: @53 = (-@53) */
  w53 = (- w53 );
  /* #723: @55 = (@52*@16) */
  w55  = (w52*w16);
  /* #724: @55 = (-@55) */
  w55 = (- w55 );
  /* #725: @41 = 00 */
  /* #726: @44 = horzcat(@53, @55, @41) */
  rr=w44;
  *rr++ = w53;
  *rr++ = w55;
  /* #727: @43 = mac(@44,@5,@43) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w43), casadi_s3, w, 0);
  /* #728: @51 = (@51+@43) */
  w51 += w43;
  /* #729: @54 = (@4*@54) */
  w54  = (w4*w54);
  /* #730: @43 = (@1*@36) */
  w43  = (w1*w36);
  /* #731: @54 = (@54+@43) */
  w54 += w43;
  /* #732: @54 = (@21*@54) */
  w54  = (w21*w54);
  /* #733: @43 = (@48*@16) */
  w43  = (w48*w16);
  /* #734: @43 = (@17*@43) */
  w43  = (w17*w43);
  /* #735: @54 = (@54+@43) */
  w54 += w43;
  /* #736: @51 = (@51-@54) */
  w51 -= w54;
  /* #737: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #738: @36 = (@2*@36) */
  w36  = (w2*w36);
  /* #739: @25 = (@25+@36) */
  w25 += w36;
  /* #740: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #741: @16 = (@35*@16) */
  w16  = (w35*w16);
  /* #742: @16 = (@23*@16) */
  w16  = (w23*w16);
  /* #743: @25 = (@25-@16) */
  w25 -= w16;
  /* #744: @51 = (@51-@25) */
  w51 -= w25;
  /* #745: output[1][23] = @51 */
  if (res[1]) res[1][55] = w51;
  /* #746: {@51, @25, @16, NULL, NULL, @36, @54, @43, NULL} = vertsplit(@34) */
  w51 = w34[0];
  w25 = w34[1];
  w16 = w34[2];
  w36 = w34[5];
  w54 = w34[6];
  w43 = w34[7];
  /* #747: @53 = (@3*@43) */
  w53  = (w3*w43);
  /* #748: @13 = vertcat(@54, @43, @53) */
  rr=w13;
  *rr++ = w54;
  *rr++ = w43;
  *rr++ = w53;
  /* #749: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #750: @18 = vertcat(@51, @25, @16) */
  rr=w18;
  *rr++ = w51;
  *rr++ = w25;
  *rr++ = w16;
  /* #751: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #752: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #753: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #754: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #755: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #756: @41 = 00 */
  /* #757: @42 = 00 */
  /* #758: @54 = (@11*@25) */
  w54  = (w11*w25);
  /* #759: @43 = horzcat(@41, @42, @54) */
  rr=(&w43);
  *rr++ = w54;
  /* #760: @43 = @43' */
  /* #761: @41 = 00 */
  /* #762: @42 = 00 */
  /* #763: @54 = (@12*@51) */
  w54  = (w12*w51);
  /* #764: @53 = horzcat(@41, @42, @54) */
  rr=(&w53);
  *rr++ = w54;
  /* #765: @53 = @53' */
  /* #766: @54 = (@9*@25) */
  w54  = (w9*w25);
  /* #767: @55 = (@14*@51) */
  w55  = (w14*w51);
  /* #768: @41 = 00 */
  /* #769: @44 = horzcat(@54, @55, @41) */
  rr=w44;
  *rr++ = w54;
  *rr++ = w55;
  /* #770: @44 = @44' */
  /* #771: @45 = horzcat(@43, @53, @44) */
  rr=w45;
  *rr++ = w43;
  *rr++ = w53;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #772: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #773: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #774: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #775: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #776: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #777: output[1][24] = @13 */
  if (res[1]) casadi_copy(w13, 3, res[1]+56);
  /* #778: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #779: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #780: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #781: @38 = (@38*@36) */
  w38 *= w36;
  /* #782: @38 = (-@38) */
  w38 = (- w38 );
  /* #783: @37 = (@37*@36) */
  w37 *= w36;
  /* #784: @37 = (-@37) */
  w37 = (- w37 );
  /* #785: @41 = 00 */
  /* #786: @44 = horzcat(@38, @37, @41) */
  rr=w44;
  *rr++ = w38;
  *rr++ = w37;
  /* #787: @44 = @44' */
  /* #788: @39 = (@39*@36) */
  w39 *= w36;
  /* #789: @47 = (@47*@36) */
  w47 *= w36;
  /* #790: @47 = (-@47) */
  w47 = (- w47 );
  /* #791: @41 = 00 */
  /* #792: @49 = horzcat(@39, @47, @41) */
  rr=w49;
  *rr++ = w39;
  *rr++ = w47;
  /* #793: @49 = @49' */
  /* #794: @41 = zeros(3x1,0nz) */
  /* #795: @46 = horzcat(@44, @49, @41) */
  rr=w46;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  /* #796: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #797: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #798: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #799: output[1][25] = @15 */
  if (res[1]) casadi_copy(w15, 3, res[1]+59);
  /* #800: @39 = 0 */
  w39 = 0.;
  /* #801: @39 = mac(@6,@13,@39) */
  for (i=0, rr=(&w39); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #802: @47 = 0 */
  w47 = 0.;
  /* #803: @50 = (@50*@36) */
  w50 *= w36;
  /* #804: @50 = (-@50) */
  w50 = (- w50 );
  /* #805: @52 = (@52*@36) */
  w52 *= w36;
  /* #806: @52 = (-@52) */
  w52 = (- w52 );
  /* #807: @41 = 00 */
  /* #808: @44 = horzcat(@50, @52, @41) */
  rr=w44;
  *rr++ = w50;
  *rr++ = w52;
  /* #809: @47 = mac(@44,@5,@47) */
  casadi_mtimes(w44, casadi_s4, w5, casadi_s1, (&w47), casadi_s3, w, 0);
  /* #810: @39 = (@39+@47) */
  w39 += w47;
  /* #811: @51 = (@4*@51) */
  w51  = (w4*w51);
  /* #812: @47 = (@1*@16) */
  w47  = (w1*w16);
  /* #813: @51 = (@51+@47) */
  w51 += w47;
  /* #814: @51 = (@21*@51) */
  w51  = (w21*w51);
  /* #815: @48 = (@48*@36) */
  w48 *= w36;
  /* #816: @48 = (@17*@48) */
  w48  = (w17*w48);
  /* #817: @51 = (@51+@48) */
  w51 += w48;
  /* #818: @39 = (@39-@51) */
  w39 -= w51;
  /* #819: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #820: @16 = (@2*@16) */
  w16  = (w2*w16);
  /* #821: @25 = (@25+@16) */
  w25 += w16;
  /* #822: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #823: @35 = (@35*@36) */
  w35 *= w36;
  /* #824: @35 = (@23*@35) */
  w35  = (w23*w35);
  /* #825: @25 = (@25-@35) */
  w25 -= w35;
  /* #826: @39 = (@39-@25) */
  w39 -= w25;
  /* #827: output[1][26] = @39 */
  if (res[1]) res[1][62] = w39;
  /* #828: @44 = zeros(2x9,2nz) */
  casadi_clear(w44, 2);
  /* #829: @41 = zeros(3x1,0nz) */
  /* #830: @42 = zeros(3x1,0nz) */
  /* #831: @49 = ones(2x1) */
  casadi_fill(w49, 2, 1.);
  /* #832: {@39, @25} = vertsplit(@49) */
  w39 = w49[0];
  w25 = w49[1];
  /* #833: @56 = 00 */
  /* #834: @49 = vertcat(@41, @42, @39, @25, @56) */
  rr=w49;
  *rr++ = w39;
  *rr++ = w25;
  /* #835: @57 = @49[:2] */
  for (rr=w57, ss=w49+0; ss!=w49+2; ss+=1) *rr++ = *ss;
  /* #836: (@44[:2] = @57) */
  for (rr=w44+0, ss=w57; rr!=w44+2; rr+=1) *rr = *ss++;
  /* #837: @57 = @44' */
  casadi_trans(w44,casadi_s6, w57, casadi_s5, iw);
  /* #838: @58 = project(@57) */
  casadi_project(w57, casadi_s5, w58, casadi_s7, w);
  /* #839: @59 = input[2][0] */
  casadi_copy(arg[2], 18, w59);
  /* #840: {@34, @33} = horzsplit(@59) */
  casadi_copy(w59, 9, w34);
  casadi_copy(w59+9, 9, w33);
  /* #841: {@39, @25, @35, NULL, NULL, @36, @16, @51, NULL} = vertsplit(@34) */
  w39 = w34[0];
  w25 = w34[1];
  w35 = w34[2];
  w36 = w34[5];
  w16 = w34[6];
  w51 = w34[7];
  /* #842: @48 = (@3*@51) */
  w48  = (w3*w51);
  /* #843: @13 = vertcat(@16, @51, @48) */
  rr=w13;
  *rr++ = w16;
  *rr++ = w51;
  *rr++ = w48;
  /* #844: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #845: @18 = vertcat(@39, @25, @35) */
  rr=w18;
  *rr++ = w39;
  *rr++ = w25;
  *rr++ = w35;
  /* #846: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #847: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #848: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #849: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #850: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #851: @41 = 00 */
  /* #852: @42 = 00 */
  /* #853: @16 = (@11*@25) */
  w16  = (w11*w25);
  /* #854: @51 = horzcat(@41, @42, @16) */
  rr=(&w51);
  *rr++ = w16;
  /* #855: @51 = @51' */
  /* #856: @41 = 00 */
  /* #857: @42 = 00 */
  /* #858: @16 = (@12*@39) */
  w16  = (w12*w39);
  /* #859: @48 = horzcat(@41, @42, @16) */
  rr=(&w48);
  *rr++ = w16;
  /* #860: @48 = @48' */
  /* #861: @16 = (@9*@25) */
  w16  = (w9*w25);
  /* #862: @47 = (@14*@39) */
  w47  = (w14*w39);
  /* #863: @41 = 00 */
  /* #864: @57 = horzcat(@16, @47, @41) */
  rr=w57;
  *rr++ = w16;
  *rr++ = w47;
  /* #865: @57 = @57' */
  /* #866: @45 = horzcat(@51, @48, @57) */
  rr=w45;
  *rr++ = w51;
  *rr++ = w48;
  for (i=0, cs=w57; i<2; ++i) *rr++ = *cs++;
  /* #867: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #868: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #869: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #870: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #871: @13 = (@0*@13) */
  for (i=0, rr=w13, cr=w0, cs=w13; i<3; ++i) (*rr++)  = ((*cr++)*(*cs++));
  /* #872: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #873: @15 = mac(@22,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #874: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #875: @51 = sin(@10) */
  w51 = sin( w10 );
  /* #876: @48 = (@51*@36) */
  w48  = (w51*w36);
  /* #877: @48 = (-@48) */
  w48 = (- w48 );
  /* #878: @16 = cos(@10) */
  w16 = cos( w10 );
  /* #879: @47 = (@16*@36) */
  w47  = (w16*w36);
  /* #880: @47 = (-@47) */
  w47 = (- w47 );
  /* #881: @41 = 00 */
  /* #882: @57 = horzcat(@48, @47, @41) */
  rr=w57;
  *rr++ = w48;
  *rr++ = w47;
  /* #883: @57 = @57' */
  /* #884: @48 = cos(@10) */
  w48 = cos( w10 );
  /* #885: @47 = (@48*@36) */
  w47  = (w48*w36);
  /* #886: @50 = sin(@10) */
  w50 = sin( w10 );
  /* #887: @52 = (@50*@36) */
  w52  = (w50*w36);
  /* #888: @52 = (-@52) */
  w52 = (- w52 );
  /* #889: @41 = 00 */
  /* #890: @44 = horzcat(@47, @52, @41) */
  rr=w44;
  *rr++ = w47;
  *rr++ = w52;
  /* #891: @44 = @44' */
  /* #892: @41 = zeros(3x1,0nz) */
  /* #893: @46 = horzcat(@57, @44, @41) */
  rr=w46;
  for (i=0, cs=w57; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #894: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #895: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #896: @15 = (@15+@18) */
  for (i=0, rr=w15, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #897: @41 = 00 */
  /* #898: @42 = 00 */
  /* #899: @47 = 0 */
  w47 = 0.;
  /* #900: @47 = mac(@6,@13,@47) */
  for (i=0, rr=(&w47); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #901: @52 = 0 */
  w52 = 0.;
  /* #902: @38 = sin(@10) */
  w38 = sin( w10 );
  /* #903: @37 = (@38*@36) */
  w37  = (w38*w36);
  /* #904: @37 = (-@37) */
  w37 = (- w37 );
  /* #905: @43 = cos(@10) */
  w43 = cos( w10 );
  /* #906: @53 = (@43*@36) */
  w53  = (w43*w36);
  /* #907: @53 = (-@53) */
  w53 = (- w53 );
  /* #908: @56 = 00 */
  /* #909: @57 = horzcat(@37, @53, @56) */
  rr=w57;
  *rr++ = w37;
  *rr++ = w53;
  /* #910: @52 = mac(@57,@5,@52) */
  casadi_mtimes(w57, casadi_s4, w5, casadi_s1, (&w52), casadi_s3, w, 0);
  /* #911: @47 = (@47+@52) */
  w47 += w52;
  /* #912: @39 = (@4*@39) */
  w39  = (w4*w39);
  /* #913: @52 = (@1*@35) */
  w52  = (w1*w35);
  /* #914: @39 = (@39+@52) */
  w39 += w52;
  /* #915: @39 = (@21*@39) */
  w39  = (w21*w39);
  /* #916: @52 = cos(@10) */
  w52 = cos( w10 );
  /* #917: @37 = (@52*@36) */
  w37  = (w52*w36);
  /* #918: @37 = (@17*@37) */
  w37  = (w17*w37);
  /* #919: @39 = (@39+@37) */
  w39 += w37;
  /* #920: @47 = (@47-@39) */
  w47 -= w39;
  /* #921: @25 = (@4*@25) */
  w25  = (w4*w25);
  /* #922: @35 = (@2*@35) */
  w35  = (w2*w35);
  /* #923: @25 = (@25+@35) */
  w25 += w35;
  /* #924: @25 = (@24*@25) */
  w25  = (w24*w25);
  /* #925: @10 = sin(@10) */
  w10 = sin( w10 );
  /* #926: @36 = (@10*@36) */
  w36  = (w10*w36);
  /* #927: @36 = (@23*@36) */
  w36  = (w23*w36);
  /* #928: @25 = (@25-@36) */
  w25 -= w36;
  /* #929: @47 = (@47-@25) */
  w47 -= w25;
  /* #930: @60 = vertcat(@13, @15, @41, @42, @47) */
  rr=w60;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  *rr++ = w47;
  /* #931: {@47, @25, @36, NULL, NULL, @35, @39, @37, NULL} = vertsplit(@33) */
  w47 = w33[0];
  w25 = w33[1];
  w36 = w33[2];
  w35 = w33[5];
  w39 = w33[6];
  w37 = w33[7];
  /* #932: @3 = (@3*@37) */
  w3 *= w37;
  /* #933: @13 = vertcat(@39, @37, @3) */
  rr=w13;
  *rr++ = w39;
  *rr++ = w37;
  *rr++ = w3;
  /* #934: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #935: @18 = vertcat(@47, @25, @36) */
  rr=w18;
  *rr++ = w47;
  *rr++ = w25;
  *rr++ = w36;
  /* #936: @15 = mac(@7,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #937: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #938: @15 = zeros(3x1) */
  casadi_clear(w15, 3);
  /* #939: @15 = mac(@20,@18,@15) */
  for (i=0, rr=w15; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #940: @40 = zeros(3x1) */
  casadi_clear(w40, 3);
  /* #941: @41 = 00 */
  /* #942: @42 = 00 */
  /* #943: @11 = (@11*@25) */
  w11 *= w25;
  /* #944: @39 = horzcat(@41, @42, @11) */
  rr=(&w39);
  *rr++ = w11;
  /* #945: @39 = @39' */
  /* #946: @41 = 00 */
  /* #947: @42 = 00 */
  /* #948: @12 = (@12*@47) */
  w12 *= w47;
  /* #949: @11 = horzcat(@41, @42, @12) */
  rr=(&w11);
  *rr++ = w12;
  /* #950: @11 = @11' */
  /* #951: @9 = (@9*@25) */
  w9 *= w25;
  /* #952: @14 = (@14*@47) */
  w14 *= w47;
  /* #953: @41 = 00 */
  /* #954: @57 = horzcat(@9, @14, @41) */
  rr=w57;
  *rr++ = w9;
  *rr++ = w14;
  /* #955: @57 = @57' */
  /* #956: @45 = horzcat(@39, @11, @57) */
  rr=w45;
  *rr++ = w39;
  *rr++ = w11;
  for (i=0, cs=w57; i<2; ++i) *rr++ = *cs++;
  /* #957: @46 = @45' */
  casadi_trans(w45,casadi_s0, w46, casadi_s0, iw);
  /* #958: @40 = mac(@46,@8,@40) */
  casadi_mtimes(w46, casadi_s0, w8, casadi_s1, w40, casadi_s1, w, 0);
  /* #959: @15 = (@15+@40) */
  for (i=0, rr=w15, cs=w40; i<3; ++i) (*rr++) += (*cs++);
  /* #960: @13 = (@13-@15) */
  for (i=0, rr=w13, cs=w15; i<3; ++i) (*rr++) -= (*cs++);
  /* #961: @0 = (@0*@13) */
  for (i=0, rr=w0, cs=w13; i<3; ++i) (*rr++) *= (*cs++);
  /* #962: @13 = zeros(3x1) */
  casadi_clear(w13, 3);
  /* #963: @13 = mac(@22,@18,@13) */
  for (i=0, rr=w13; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w22+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #964: @18 = zeros(3x1) */
  casadi_clear(w18, 3);
  /* #965: @51 = (@51*@35) */
  w51 *= w35;
  /* #966: @51 = (-@51) */
  w51 = (- w51 );
  /* #967: @16 = (@16*@35) */
  w16 *= w35;
  /* #968: @16 = (-@16) */
  w16 = (- w16 );
  /* #969: @41 = 00 */
  /* #970: @57 = horzcat(@51, @16, @41) */
  rr=w57;
  *rr++ = w51;
  *rr++ = w16;
  /* #971: @57 = @57' */
  /* #972: @48 = (@48*@35) */
  w48 *= w35;
  /* #973: @50 = (@50*@35) */
  w50 *= w35;
  /* #974: @50 = (-@50) */
  w50 = (- w50 );
  /* #975: @41 = 00 */
  /* #976: @44 = horzcat(@48, @50, @41) */
  rr=w44;
  *rr++ = w48;
  *rr++ = w50;
  /* #977: @44 = @44' */
  /* #978: @41 = zeros(3x1,0nz) */
  /* #979: @46 = horzcat(@57, @44, @41) */
  rr=w46;
  for (i=0, cs=w57; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #980: @45 = @46' */
  casadi_trans(w46,casadi_s2, w45, casadi_s2, iw);
  /* #981: @18 = mac(@45,@8,@18) */
  casadi_mtimes(w45, casadi_s2, w8, casadi_s1, w18, casadi_s1, w, 0);
  /* #982: @13 = (@13+@18) */
  for (i=0, rr=w13, cs=w18; i<3; ++i) (*rr++) += (*cs++);
  /* #983: @41 = 00 */
  /* #984: @42 = 00 */
  /* #985: @48 = 0 */
  w48 = 0.;
  /* #986: @48 = mac(@6,@0,@48) */
  for (i=0, rr=(&w48); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #987: @50 = 0 */
  w50 = 0.;
  /* #988: @38 = (@38*@35) */
  w38 *= w35;
  /* #989: @38 = (-@38) */
  w38 = (- w38 );
  /* #990: @43 = (@43*@35) */
  w43 *= w35;
  /* #991: @43 = (-@43) */
  w43 = (- w43 );
  /* #992: @56 = 00 */
  /* #993: @57 = horzcat(@38, @43, @56) */
  rr=w57;
  *rr++ = w38;
  *rr++ = w43;
  /* #994: @50 = mac(@57,@5,@50) */
  casadi_mtimes(w57, casadi_s4, w5, casadi_s1, (&w50), casadi_s3, w, 0);
  /* #995: @48 = (@48+@50) */
  w48 += w50;
  /* #996: @47 = (@4*@47) */
  w47  = (w4*w47);
  /* #997: @1 = (@1*@36) */
  w1 *= w36;
  /* #998: @47 = (@47+@1) */
  w47 += w1;
  /* #999: @21 = (@21*@47) */
  w21 *= w47;
  /* #1000: @52 = (@52*@35) */
  w52 *= w35;
  /* #1001: @17 = (@17*@52) */
  w17 *= w52;
  /* #1002: @21 = (@21+@17) */
  w21 += w17;
  /* #1003: @48 = (@48-@21) */
  w48 -= w21;
  /* #1004: @4 = (@4*@25) */
  w4 *= w25;
  /* #1005: @2 = (@2*@36) */
  w2 *= w36;
  /* #1006: @4 = (@4+@2) */
  w4 += w2;
  /* #1007: @24 = (@24*@4) */
  w24 *= w4;
  /* #1008: @10 = (@10*@35) */
  w10 *= w35;
  /* #1009: @23 = (@23*@10) */
  w23 *= w10;
  /* #1010: @24 = (@24-@23) */
  w24 -= w23;
  /* #1011: @48 = (@48-@24) */
  w48 -= w24;
  /* #1012: @61 = vertcat(@0, @13, @41, @42, @48) */
  rr=w61;
  for (i=0, cs=w0; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<3; ++i) *rr++ = *cs++;
  *rr++ = w48;
  /* #1013: @62 = horzcat(@60, @61) */
  rr=w62;
  for (i=0, cs=w60; i<7; ++i) *rr++ = *cs++;
  for (i=0, cs=w61; i<7; ++i) *rr++ = *cs++;
  /* #1014: @63 = project(@62) */
  casadi_project(w62, casadi_s8, w63, casadi_s7, w);
  /* #1015: @58 = (@58+@63) */
  for (i=0, rr=w58, cs=w63; i<16; ++i) (*rr++) += (*cs++);
  /* #1016: output[2][0] = @58 */
  casadi_copy(w58, 16, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void simple_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int simple_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real simple_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* simple_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    case 3: return casadi_s12;
    case 4: return casadi_s13;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* simple_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s14;
    case 2: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int simple_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 10;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 4;
  if (sz_w) *sz_w = 343;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
